# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct FinalSurfacesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `FinalSurfacesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ FinalSurfacesApi }) = "http://localhost/torc-service/v1"

const _returntypes_claim_action_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ClaimActionResponse,
)

function _oacinternal_claim_action(_api::FinalSurfacesApi, id::Int64, action_id::Int64, claim_action_request::ClaimActionRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_claim_action_FinalSurfacesApi, "/workflows/{id}/actions/{action_id}/claim", [], claim_action_request)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.path, "action_id", action_id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- action_id::Int64 (required)
- claim_action_request::ClaimActionRequest (required)

Return: ClaimActionResponse, OpenAPI.Clients.ApiResponse
"""
function claim_action(_api::FinalSurfacesApi, id::Int64, action_id::Int64, claim_action_request::ClaimActionRequest; _mediaType=nothing)
    _ctx = _oacinternal_claim_action(_api, id, action_id, claim_action_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function claim_action(_api::FinalSurfacesApi, response_stream::Channel, id::Int64, action_id::Int64, claim_action_request::ClaimActionRequest; _mediaType=nothing)
    _ctx = _oacinternal_claim_action(_api, id, action_id, claim_action_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_remote_workers_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{RemoteWorkerModel},
)

function _oacinternal_create_remote_workers(_api::FinalSurfacesApi, id::Int64, request_body::Vector{String}; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_remote_workers_FinalSurfacesApi, "/workflows/{id}/remote_workers", [], request_body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- request_body::Vector{String} (required)

Return: Vector{RemoteWorkerModel}, OpenAPI.Clients.ApiResponse
"""
function create_remote_workers(_api::FinalSurfacesApi, id::Int64, request_body::Vector{String}; _mediaType=nothing)
    _ctx = _oacinternal_create_remote_workers(_api, id, request_body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_remote_workers(_api::FinalSurfacesApi, response_stream::Channel, id::Int64, request_body::Vector{String}; _mediaType=nothing)
    _ctx = _oacinternal_create_remote_workers(_api, id, request_body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_ro_crate_entity_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RoCrateEntityModel,
)

function _oacinternal_create_ro_crate_entity(_api::FinalSurfacesApi, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_ro_crate_entity_FinalSurfacesApi, "/ro_crate_entities", [], ro_crate_entity_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- ro_crate_entity_model::RoCrateEntityModel (required)

Return: RoCrateEntityModel, OpenAPI.Clients.ApiResponse
"""
function create_ro_crate_entity(_api::FinalSurfacesApi, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_create_ro_crate_entity(_api, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_ro_crate_entity(_api::FinalSurfacesApi, response_stream::Channel, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_create_ro_crate_entity(_api, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_workflow_action_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => WorkflowActionModel,
)

function _oacinternal_create_workflow_action(_api::FinalSurfacesApi, id::Int64, workflow_action_model::WorkflowActionModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_workflow_action_FinalSurfacesApi, "/workflows/{id}/actions", [], workflow_action_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- workflow_action_model::WorkflowActionModel (required)

Return: WorkflowActionModel, OpenAPI.Clients.ApiResponse
"""
function create_workflow_action(_api::FinalSurfacesApi, id::Int64, workflow_action_model::WorkflowActionModel; _mediaType=nothing)
    _ctx = _oacinternal_create_workflow_action(_api, id, workflow_action_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_workflow_action(_api::FinalSurfacesApi, response_stream::Channel, id::Int64, workflow_action_model::WorkflowActionModel; _mediaType=nothing)
    _ctx = _oacinternal_create_workflow_action(_api, id, workflow_action_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_remote_worker_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RemoteWorkerModel,
)

function _oacinternal_delete_remote_worker(_api::FinalSurfacesApi, id::Int64, worker::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_remote_worker_FinalSurfacesApi, "/workflows/{id}/remote_workers/{worker}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.path, "worker", worker)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- worker::String (required)

Return: RemoteWorkerModel, OpenAPI.Clients.ApiResponse
"""
function delete_remote_worker(_api::FinalSurfacesApi, id::Int64, worker::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_remote_worker(_api, id, worker; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_remote_worker(_api::FinalSurfacesApi, response_stream::Channel, id::Int64, worker::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_remote_worker(_api, id, worker; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_ro_crate_entities_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeleteRoCrateEntitiesResponse,
)

function _oacinternal_delete_ro_crate_entities(_api::FinalSurfacesApi, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_ro_crate_entities_FinalSurfacesApi, "/workflows/{id}/ro_crate_entities", [], body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- body::Any

Return: DeleteRoCrateEntitiesResponse, OpenAPI.Clients.ApiResponse
"""
function delete_ro_crate_entities(_api::FinalSurfacesApi, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entities(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_ro_crate_entities(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entities(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_ro_crate_entity_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => MessageResponse,
)

function _oacinternal_delete_ro_crate_entity(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_ro_crate_entity_FinalSurfacesApi, "/ro_crate_entities/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: MessageResponse, OpenAPI.Clients.ApiResponse
"""
function delete_ro_crate_entity(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_ro_crate_entity(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_pending_actions_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{WorkflowActionModel},
)

function _oacinternal_get_pending_actions(_api::FinalSurfacesApi, id::Int64; trigger_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_pending_actions_FinalSurfacesApi, "/workflows/{id}/actions/pending", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "trigger_type", trigger_type; style="form", is_explode=true)  # type Vector{String}
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- trigger_type::Vector{String}

Return: Vector{WorkflowActionModel}, OpenAPI.Clients.ApiResponse
"""
function get_pending_actions(_api::FinalSurfacesApi, id::Int64; trigger_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_pending_actions(_api, id; trigger_type=trigger_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_pending_actions(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; trigger_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_pending_actions(_api, id; trigger_type=trigger_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_ro_crate_entity_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RoCrateEntityModel,
)

function _oacinternal_get_ro_crate_entity(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_ro_crate_entity_FinalSurfacesApi, "/ro_crate_entities/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: RoCrateEntityModel, OpenAPI.Clients.ApiResponse
"""
function get_ro_crate_entity(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_ro_crate_entity(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_workflow_actions_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{WorkflowActionModel},
)

function _oacinternal_get_workflow_actions(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_workflow_actions_FinalSurfacesApi, "/workflows/{id}/actions", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: Vector{WorkflowActionModel}, OpenAPI.Clients.ApiResponse
"""
function get_workflow_actions(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_workflow_actions(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_workflow_actions(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_workflow_actions(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_remote_workers_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{RemoteWorkerModel},
)

function _oacinternal_list_remote_workers(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_remote_workers_FinalSurfacesApi, "/workflows/{id}/remote_workers", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: Vector{RemoteWorkerModel}, OpenAPI.Clients.ApiResponse
"""
function list_remote_workers(_api::FinalSurfacesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_list_remote_workers(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_remote_workers(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_list_remote_workers(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_ro_crate_entities_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListRoCrateEntitiesResponse,
)

function _oacinternal_list_ro_crate_entities(_api::FinalSurfacesApi, id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_ro_crate_entities_FinalSurfacesApi, "/workflows/{id}/ro_crate_entities", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort_by", sort_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "reverse_sort", reverse_sort; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- offset::Int64
- limit::Int64
- sort_by::String
- reverse_sort::Bool

Return: ListRoCrateEntitiesResponse, OpenAPI.Clients.ApiResponse
"""
function list_ro_crate_entities(_api::FinalSurfacesApi, id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_ro_crate_entities(_api, id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_ro_crate_entities(_api::FinalSurfacesApi, response_stream::Channel, id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_ro_crate_entities(_api, id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_reload_auth_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ReloadAuthResponse,
)

function _oacinternal_reload_auth(_api::FinalSurfacesApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_reload_auth_FinalSurfacesApi, "/admin/reload-auth", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: ReloadAuthResponse, OpenAPI.Clients.ApiResponse
"""
function reload_auth(_api::FinalSurfacesApi; _mediaType=nothing)
    _ctx = _oacinternal_reload_auth(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function reload_auth(_api::FinalSurfacesApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_reload_auth(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_ro_crate_entity_FinalSurfacesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RoCrateEntityModel,
)

function _oacinternal_update_ro_crate_entity(_api::FinalSurfacesApi, id::Int64, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_ro_crate_entity_FinalSurfacesApi, "/ro_crate_entities/{id}", [], ro_crate_entity_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- ro_crate_entity_model::RoCrateEntityModel (required)

Return: RoCrateEntityModel, OpenAPI.Clients.ApiResponse
"""
function update_ro_crate_entity(_api::FinalSurfacesApi, id::Int64, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_update_ro_crate_entity(_api, id, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_ro_crate_entity(_api::FinalSurfacesApi, response_stream::Channel, id::Int64, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_update_ro_crate_entity(_api, id, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export claim_action
export create_remote_workers
export create_ro_crate_entity
export create_workflow_action
export delete_remote_worker
export delete_ro_crate_entities
export delete_ro_crate_entity
export get_pending_actions
export get_ro_crate_entity
export get_workflow_actions
export list_remote_workers
export list_ro_crate_entities
export reload_auth
export update_ro_crate_entity
