# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct AdminResourcesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `AdminResourcesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ AdminResourcesApi }) = "http://localhost"

const _returntypes_create_failure_handler_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => FailureHandlerModel,
)

function _oacinternal_create_failure_handler(_api::AdminResourcesApi, failure_handler_model::FailureHandlerModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_failure_handler_AdminResourcesApi, "/failure_handlers", [], failure_handler_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- failure_handler_model::FailureHandlerModel (required)

Return: FailureHandlerModel, OpenAPI.Clients.ApiResponse
"""
function create_failure_handler(_api::AdminResourcesApi, failure_handler_model::FailureHandlerModel; _mediaType=nothing)
    _ctx = _oacinternal_create_failure_handler(_api, failure_handler_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_failure_handler(_api::AdminResourcesApi, response_stream::Channel, failure_handler_model::FailureHandlerModel; _mediaType=nothing)
    _ctx = _oacinternal_create_failure_handler(_api, failure_handler_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_jobs_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => CreateJobsResponse,
)

function _oacinternal_create_jobs(_api::AdminResourcesApi, jobs_model::JobsModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_jobs_AdminResourcesApi, "/bulk_jobs", [], jobs_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- jobs_model::JobsModel (required)

Return: CreateJobsResponse, OpenAPI.Clients.ApiResponse
"""
function create_jobs(_api::AdminResourcesApi, jobs_model::JobsModel; _mediaType=nothing)
    _ctx = _oacinternal_create_jobs(_api, jobs_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_jobs(_api::AdminResourcesApi, response_stream::Channel, jobs_model::JobsModel; _mediaType=nothing)
    _ctx = _oacinternal_create_jobs(_api, jobs_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_resource_requirements_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ResourceRequirementsModel,
)

function _oacinternal_create_resource_requirements(_api::AdminResourcesApi, resource_requirements_model::ResourceRequirementsModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_resource_requirements_AdminResourcesApi, "/resource_requirements", [], resource_requirements_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- resource_requirements_model::ResourceRequirementsModel (required)

Return: ResourceRequirementsModel, OpenAPI.Clients.ApiResponse
"""
function create_resource_requirements(_api::AdminResourcesApi, resource_requirements_model::ResourceRequirementsModel; _mediaType=nothing)
    _ctx = _oacinternal_create_resource_requirements(_api, resource_requirements_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_resource_requirements(_api::AdminResourcesApi, response_stream::Channel, resource_requirements_model::ResourceRequirementsModel; _mediaType=nothing)
    _ctx = _oacinternal_create_resource_requirements(_api, resource_requirements_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_slurm_stats_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SlurmStatsModel,
)

function _oacinternal_create_slurm_stats(_api::AdminResourcesApi, slurm_stats_model::SlurmStatsModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_slurm_stats_AdminResourcesApi, "/slurm_stats", [], slurm_stats_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- slurm_stats_model::SlurmStatsModel (required)

Return: SlurmStatsModel, OpenAPI.Clients.ApiResponse
"""
function create_slurm_stats(_api::AdminResourcesApi, slurm_stats_model::SlurmStatsModel; _mediaType=nothing)
    _ctx = _oacinternal_create_slurm_stats(_api, slurm_stats_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_slurm_stats(_api::AdminResourcesApi, response_stream::Channel, slurm_stats_model::SlurmStatsModel; _mediaType=nothing)
    _ctx = _oacinternal_create_slurm_stats(_api, slurm_stats_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_failure_handler_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => FailureHandlerModel,
)

function _oacinternal_delete_failure_handler(_api::AdminResourcesApi, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_failure_handler_AdminResourcesApi, "/failure_handlers/{id}", [], body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- body::Any

Return: FailureHandlerModel, OpenAPI.Clients.ApiResponse
"""
function delete_failure_handler(_api::AdminResourcesApi, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_failure_handler(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_failure_handler(_api::AdminResourcesApi, response_stream::Channel, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_failure_handler(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_resource_requirement_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ResourceRequirementsModel,
)

function _oacinternal_delete_resource_requirement(_api::AdminResourcesApi, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_resource_requirement_AdminResourcesApi, "/resource_requirements/{id}", [], body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- body::Any

Return: ResourceRequirementsModel, OpenAPI.Clients.ApiResponse
"""
function delete_resource_requirement(_api::AdminResourcesApi, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_resource_requirement(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_resource_requirement(_api::AdminResourcesApi, response_stream::Channel, id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_resource_requirement(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_resource_requirements_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeleteCountResponse,
)

function _oacinternal_delete_resource_requirements(_api::AdminResourcesApi, workflow_id::Int64; body=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_resource_requirements_AdminResourcesApi, "/resource_requirements", [], body)
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)
- body::Any

Return: DeleteCountResponse, OpenAPI.Clients.ApiResponse
"""
function delete_resource_requirements(_api::AdminResourcesApi, workflow_id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_resource_requirements(_api, workflow_id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_resource_requirements(_api::AdminResourcesApi, response_stream::Channel, workflow_id::Int64; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_delete_resource_requirements(_api, workflow_id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_failure_handler_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => FailureHandlerModel,
)

function _oacinternal_get_failure_handler(_api::AdminResourcesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_failure_handler_AdminResourcesApi, "/failure_handlers/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: FailureHandlerModel, OpenAPI.Clients.ApiResponse
"""
function get_failure_handler(_api::AdminResourcesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_failure_handler(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_failure_handler(_api::AdminResourcesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_failure_handler(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_resource_requirements_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ResourceRequirementsModel,
)

function _oacinternal_get_resource_requirements(_api::AdminResourcesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_resource_requirements_AdminResourcesApi, "/resource_requirements/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: ResourceRequirementsModel, OpenAPI.Clients.ApiResponse
"""
function get_resource_requirements(_api::AdminResourcesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_resource_requirements(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_resource_requirements(_api::AdminResourcesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_resource_requirements(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_failure_handlers_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListFailureHandlersResponse,
)

function _oacinternal_list_failure_handlers(_api::AdminResourcesApi, id::Int64; offset=nothing, limit=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_failure_handlers_AdminResourcesApi, "/workflows/{id}/failure_handlers", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- offset::Int64
- limit::Int64

Return: ListFailureHandlersResponse, OpenAPI.Clients.ApiResponse
"""
function list_failure_handlers(_api::AdminResourcesApi, id::Int64; offset=nothing, limit=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_failure_handlers(_api, id; offset=offset, limit=limit, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_failure_handlers(_api::AdminResourcesApi, response_stream::Channel, id::Int64; offset=nothing, limit=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_failure_handlers(_api, id; offset=offset, limit=limit, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_resource_requirements_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListResourceRequirementsResponse,
)

function _oacinternal_list_resource_requirements(_api::AdminResourcesApi, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, job_id=nothing, name=nothing, memory=nothing, num_cpus=nothing, num_gpus=nothing, num_nodes=nothing, runtime=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_resource_requirements_AdminResourcesApi, "/resource_requirements", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort_by", sort_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "reverse_sort", reverse_sort; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_param(_ctx.query, "job_id", job_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "name", name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "memory", memory; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "num_cpus", num_cpus; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "num_gpus", num_gpus; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "num_nodes", num_nodes; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "runtime", runtime; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)
- offset::Int64
- limit::Int64
- sort_by::String
- reverse_sort::Bool
- job_id::Int64
- name::String
- memory::String
- num_cpus::Int64
- num_gpus::Int64
- num_nodes::Int64
- runtime::Int64

Return: ListResourceRequirementsResponse, OpenAPI.Clients.ApiResponse
"""
function list_resource_requirements(_api::AdminResourcesApi, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, job_id=nothing, name=nothing, memory=nothing, num_cpus=nothing, num_gpus=nothing, num_nodes=nothing, runtime=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_resource_requirements(_api, workflow_id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, job_id=job_id, name=name, memory=memory, num_cpus=num_cpus, num_gpus=num_gpus, num_nodes=num_nodes, runtime=runtime, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_resource_requirements(_api::AdminResourcesApi, response_stream::Channel, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, job_id=nothing, name=nothing, memory=nothing, num_cpus=nothing, num_gpus=nothing, num_nodes=nothing, runtime=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_resource_requirements(_api, workflow_id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, job_id=job_id, name=name, memory=memory, num_cpus=num_cpus, num_gpus=num_gpus, num_nodes=num_nodes, runtime=runtime, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_slurm_stats_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListSlurmStatsResponse,
)

function _oacinternal_list_slurm_stats(_api::AdminResourcesApi, workflow_id::Int64; job_id=nothing, offset=nothing, limit=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_slurm_stats_AdminResourcesApi, "/slurm_stats", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "job_id", job_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)
- job_id::Int64
- offset::Int64
- limit::Int64

Return: ListSlurmStatsResponse, OpenAPI.Clients.ApiResponse
"""
function list_slurm_stats(_api::AdminResourcesApi, workflow_id::Int64; job_id=nothing, offset=nothing, limit=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_slurm_stats(_api, workflow_id; job_id=job_id, offset=offset, limit=limit, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_slurm_stats(_api::AdminResourcesApi, response_stream::Channel, workflow_id::Int64; job_id=nothing, offset=nothing, limit=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_slurm_stats(_api, workflow_id; job_id=job_id, offset=offset, limit=limit, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_resource_requirements_AdminResourcesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ResourceRequirementsModel,
)

function _oacinternal_update_resource_requirements(_api::AdminResourcesApi, id::Int64, resource_requirements_model::ResourceRequirementsModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_resource_requirements_AdminResourcesApi, "/resource_requirements/{id}", [], resource_requirements_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- resource_requirements_model::ResourceRequirementsModel (required)

Return: ResourceRequirementsModel, OpenAPI.Clients.ApiResponse
"""
function update_resource_requirements(_api::AdminResourcesApi, id::Int64, resource_requirements_model::ResourceRequirementsModel; _mediaType=nothing)
    _ctx = _oacinternal_update_resource_requirements(_api, id, resource_requirements_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_resource_requirements(_api::AdminResourcesApi, response_stream::Channel, id::Int64, resource_requirements_model::ResourceRequirementsModel; _mediaType=nothing)
    _ctx = _oacinternal_update_resource_requirements(_api, id, resource_requirements_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_failure_handler
export create_jobs
export create_resource_requirements
export create_slurm_stats
export delete_failure_handler
export delete_resource_requirement
export delete_resource_requirements
export get_failure_handler
export get_resource_requirements
export list_failure_handlers
export list_resource_requirements
export list_slurm_stats
export update_resource_requirements
