# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""dataset_model
Data model for datasets (first-class directory outputs).

    DatasetModel(;
        id=nothing,
        workflow_id=nothing,
        name=nothing,
        path=nothing,
        description=nothing,
        hash_mode="manifest",
        status="pending",
        claimed_by_node_id=nothing,
        claimed_at=nothing,
        file_count=nothing,
        total_size_bytes=nothing,
        manifest_hash=nothing,
        finalized_at=nothing,
    )

    - id::Int64
    - workflow_id::Int64 : Database ID of the workflow this dataset belongs to.
    - name::String : User-defined name of the dataset.
    - path::String : Path to the dataset directory.
    - description::String : Optional description of the dataset.
    - hash_mode::String : Hash mode for integrity verification (manifest, content, none).
    - status::String : Dataset status (pending, finalizing, finalized).
    - claimed_by_node_id::Int64 : ID of the compute node that claimed this dataset for finalization.
    - claimed_at::Float64 : Unix timestamp when the dataset was claimed.
    - file_count::Int64 : Number of files in the dataset (set after finalization).
    - total_size_bytes::Int64 : Total size of all files in bytes (set after finalization).
    - manifest_hash::String : Hash of the dataset contents (set after finalization).
    - finalized_at::Float64 : Unix timestamp when the dataset was finalized.
"""
Base.@kwdef mutable struct DatasetModel <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    workflow_id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    path::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    hash_mode::Union{Nothing, String} = "manifest"
    status::Union{Nothing, String} = "pending"
    claimed_by_node_id::Union{Nothing, Int64} = nothing
    claimed_at::Union{Nothing, Float64} = nothing
    file_count::Union{Nothing, Int64} = nothing
    total_size_bytes::Union{Nothing, Int64} = nothing
    manifest_hash::Union{Nothing, String} = nothing
    finalized_at::Union{Nothing, Float64} = nothing

    function DatasetModel(id, workflow_id, name, path, description, hash_mode, status, claimed_by_node_id, claimed_at, file_count, total_size_bytes, manifest_hash, finalized_at, )
        o = new(id, workflow_id, name, path, description, hash_mode, status, claimed_by_node_id, claimed_at, file_count, total_size_bytes, manifest_hash, finalized_at, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DatasetModel

const _property_types_DatasetModel = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("workflow_id")=>"Int64", Symbol("name")=>"String", Symbol("path")=>"String", Symbol("description")=>"String", Symbol("hash_mode")=>"String", Symbol("status")=>"String", Symbol("claimed_by_node_id")=>"Int64", Symbol("claimed_at")=>"Float64", Symbol("file_count")=>"Int64", Symbol("total_size_bytes")=>"Int64", Symbol("manifest_hash")=>"String", Symbol("finalized_at")=>"Float64", )
OpenAPI.property_type(::Type{ DatasetModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DatasetModel[name]))}

function OpenAPI.check_required(o::DatasetModel)
    o.workflow_id === nothing && (return false)
    o.name === nothing && (return false)
    o.path === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DatasetModel)
    OpenAPI.validate_property(DatasetModel, Symbol("id"), o.id)
    OpenAPI.validate_property(DatasetModel, Symbol("workflow_id"), o.workflow_id)
    OpenAPI.validate_property(DatasetModel, Symbol("name"), o.name)
    OpenAPI.validate_property(DatasetModel, Symbol("path"), o.path)
    OpenAPI.validate_property(DatasetModel, Symbol("description"), o.description)
    OpenAPI.validate_property(DatasetModel, Symbol("hash_mode"), o.hash_mode)
    OpenAPI.validate_property(DatasetModel, Symbol("status"), o.status)
    OpenAPI.validate_property(DatasetModel, Symbol("claimed_by_node_id"), o.claimed_by_node_id)
    OpenAPI.validate_property(DatasetModel, Symbol("claimed_at"), o.claimed_at)
    OpenAPI.validate_property(DatasetModel, Symbol("file_count"), o.file_count)
    OpenAPI.validate_property(DatasetModel, Symbol("total_size_bytes"), o.total_size_bytes)
    OpenAPI.validate_property(DatasetModel, Symbol("manifest_hash"), o.manifest_hash)
    OpenAPI.validate_property(DatasetModel, Symbol("finalized_at"), o.finalized_at)
end

function OpenAPI.validate_property(::Type{ DatasetModel }, name::Symbol, val)






    if name === Symbol("hash_mode")
        OpenAPI.validate_param(name, "DatasetModel", :enum, val, ["manifest", "content", "none"])
    end


    if name === Symbol("status")
        OpenAPI.validate_param(name, "DatasetModel", :enum, val, ["pending", "finalizing", "finalized"])
    end







end
