# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SlurmJobCorrelationModel
One Slurm-job-to-Torc-job correlation row: the Slurm job that ran a given Torc job, derived from scheduled_compute_node -&gt; compute_node -&gt; result.

    SlurmJobCorrelationModel(;
        job_id=nothing,
        job_name=nothing,
        slurm_job_id=nothing,
    )

    - job_id::Int64
    - job_name::String
    - slurm_job_id::String
"""
Base.@kwdef mutable struct SlurmJobCorrelationModel <: OpenAPI.APIModel
    job_id::Union{Nothing, Int64} = nothing
    job_name::Union{Nothing, String} = nothing
    slurm_job_id::Union{Nothing, String} = nothing

    function SlurmJobCorrelationModel(job_id, job_name, slurm_job_id, )
        o = new(job_id, job_name, slurm_job_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SlurmJobCorrelationModel

const _property_types_SlurmJobCorrelationModel = Dict{Symbol,String}(Symbol("job_id")=>"Int64", Symbol("job_name")=>"String", Symbol("slurm_job_id")=>"String", )
OpenAPI.property_type(::Type{ SlurmJobCorrelationModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SlurmJobCorrelationModel[name]))}

function OpenAPI.check_required(o::SlurmJobCorrelationModel)
    o.job_id === nothing && (return false)
    o.job_name === nothing && (return false)
    o.slurm_job_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SlurmJobCorrelationModel)
    OpenAPI.validate_property(SlurmJobCorrelationModel, Symbol("job_id"), o.job_id)
    OpenAPI.validate_property(SlurmJobCorrelationModel, Symbol("job_name"), o.job_name)
    OpenAPI.validate_property(SlurmJobCorrelationModel, Symbol("slurm_job_id"), o.slurm_job_id)
end

function OpenAPI.validate_property(::Type{ SlurmJobCorrelationModel }, name::Symbol, val)

    if name === Symbol("job_id")
        OpenAPI.validate_param(name, "SlurmJobCorrelationModel", :format, val, "int64")
    end


end
