# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RunningJobModel
A currently-running job together with the compute node it occupies and, when the node was provisioned by a scheduler, that scheduler&#39;s job ID. &#x60;scheduler_type&#x60; is generic (e.g. \&quot;slurm\&quot;, \&quot;local\&quot;); &#x60;scheduler_job_id&#x60; is populated only for scheduler-managed nodes (the Slurm job ID today).

    RunningJobModel(;
        compute_node_name=nothing,
        job_id=nothing,
        job_name=nothing,
        scheduler_job_id=nothing,
        scheduler_type=nothing,
        start_time=nothing,
    )

    - compute_node_name::String
    - job_id::Int64
    - job_name::String
    - scheduler_job_id::String
    - scheduler_type::String
    - start_time::String : RFC3339 time the job started running, for computing elapsed time.
"""
Base.@kwdef mutable struct RunningJobModel <: OpenAPI.APIModel
    compute_node_name::Union{Nothing, String} = nothing
    job_id::Union{Nothing, Int64} = nothing
    job_name::Union{Nothing, String} = nothing
    scheduler_job_id::Union{Nothing, String} = nothing
    scheduler_type::Union{Nothing, String} = nothing
    start_time::Union{Nothing, String} = nothing

    function RunningJobModel(compute_node_name, job_id, job_name, scheduler_job_id, scheduler_type, start_time, )
        o = new(compute_node_name, job_id, job_name, scheduler_job_id, scheduler_type, start_time, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RunningJobModel

const _property_types_RunningJobModel = Dict{Symbol,String}(Symbol("compute_node_name")=>"String", Symbol("job_id")=>"Int64", Symbol("job_name")=>"String", Symbol("scheduler_job_id")=>"String", Symbol("scheduler_type")=>"String", Symbol("start_time")=>"String", )
OpenAPI.property_type(::Type{ RunningJobModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RunningJobModel[name]))}

function OpenAPI.check_required(o::RunningJobModel)
    o.compute_node_name === nothing && (return false)
    o.job_id === nothing && (return false)
    o.job_name === nothing && (return false)
    o.scheduler_type === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RunningJobModel)
    OpenAPI.validate_property(RunningJobModel, Symbol("compute_node_name"), o.compute_node_name)
    OpenAPI.validate_property(RunningJobModel, Symbol("job_id"), o.job_id)
    OpenAPI.validate_property(RunningJobModel, Symbol("job_name"), o.job_name)
    OpenAPI.validate_property(RunningJobModel, Symbol("scheduler_job_id"), o.scheduler_job_id)
    OpenAPI.validate_property(RunningJobModel, Symbol("scheduler_type"), o.scheduler_type)
    OpenAPI.validate_property(RunningJobModel, Symbol("start_time"), o.start_time)
end

function OpenAPI.validate_property(::Type{ RunningJobModel }, name::Symbol, val)


    if name === Symbol("job_id")
        OpenAPI.validate_param(name, "RunningJobModel", :format, val, "int64")
    end




end
