# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExecutionConfig
Unified execution configuration that controls how jobs are run.  Used both as the user-authored &#x60;WorkflowSpec.execution_config&#x60; and as the persisted &#x60;WorkflowModel.execution_config&#x60; (stored as JSON in the &#x60;workflow.execution_config&#x60; column).

    ExecutionConfig(;
        enable_cpu_bind=nothing,
        job_stdio_overrides=nothing,
        limit_resources=nothing,
        mode=nothing,
        oom_exit_code=nothing,
        sigkill_headroom_seconds=nothing,
        sigterm_lead_seconds=nothing,
        srun_mpi=nothing,
        srun_termination_signal=nothing,
        staggered_start=nothing,
        stdio=nothing,
        termination_signal=nothing,
        timeout_exit_code=nothing,
    )

    - enable_cpu_bind::Bool : When true, allow Slurm to bind tasks to specific CPU cores (slurm mode only).
    - job_stdio_overrides::Dict{String, StdioConfig} : Per-job stdio overrides keyed by job name. Populated during workflow creation from per-job &#x60;stdio&#x60; fields in the spec.
    - limit_resources::Bool : When true (default), monitor memory/CPU usage and kill jobs that exceed their resource requirements (OOM enforcement). Only applies in direct mode.
    - mode::ExecutionMode : Execution mode: direct (default), slurm, or auto.
    - oom_exit_code::Int64 : Exit code to use when a job is OOM-killed (direct mode only). Default: 137 (128 + SIGKILL &#x3D; 128 + 9).
    - sigkill_headroom_seconds::Int64 : Seconds before end_time to send SIGKILL (direct mode) or set srun --time (slurm mode). Default: 60.
    - sigterm_lead_seconds::Int64 : Seconds before SIGKILL to send the termination signal (direct mode only). Default: 30.
    - srun_mpi::String : MPI launcher mode for the outer &#x60;srun&#x60; used to launch one job runner per allocated node.
    - srun_termination_signal::String : Signal specification for srun steps, passed as &#x60;srun --signal&#x3D;&lt;value&gt;&#x60; (slurm mode only).
    - staggered_start::Bool : Enable staggered startup for job runners to mitigate thundering herd.
    - stdio::StdioConfig : Workflow-level default for stdout/stderr capture.
    - termination_signal::String : Signal to send before SIGKILL for graceful termination (direct mode only). Default: \&quot;SIGTERM\&quot;.
    - timeout_exit_code::Int64 : Exit code to use when a job times out. Default: 152 (matches Slurm&#39;s TIMEOUT exit code).
"""
Base.@kwdef mutable struct ExecutionConfig <: OpenAPI.APIModel
    enable_cpu_bind::Union{Nothing, Bool} = nothing
    job_stdio_overrides::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, StdioConfig} }
    limit_resources::Union{Nothing, Bool} = nothing
    mode = nothing # spec type: Union{ Nothing, ExecutionMode }
    oom_exit_code::Union{Nothing, Int64} = nothing
    sigkill_headroom_seconds::Union{Nothing, Int64} = nothing
    sigterm_lead_seconds::Union{Nothing, Int64} = nothing
    srun_mpi::Union{Nothing, String} = nothing
    srun_termination_signal::Union{Nothing, String} = nothing
    staggered_start::Union{Nothing, Bool} = nothing
    stdio = nothing # spec type: Union{ Nothing, StdioConfig }
    termination_signal::Union{Nothing, String} = nothing
    timeout_exit_code::Union{Nothing, Int64} = nothing

    function ExecutionConfig(enable_cpu_bind, job_stdio_overrides, limit_resources, mode, oom_exit_code, sigkill_headroom_seconds, sigterm_lead_seconds, srun_mpi, srun_termination_signal, staggered_start, stdio, termination_signal, timeout_exit_code, )
        o = new(enable_cpu_bind, job_stdio_overrides, limit_resources, mode, oom_exit_code, sigkill_headroom_seconds, sigterm_lead_seconds, srun_mpi, srun_termination_signal, staggered_start, stdio, termination_signal, timeout_exit_code, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ExecutionConfig

const _property_types_ExecutionConfig = Dict{Symbol,String}(Symbol("enable_cpu_bind")=>"Bool", Symbol("job_stdio_overrides")=>"Dict{String, StdioConfig}", Symbol("limit_resources")=>"Bool", Symbol("mode")=>"ExecutionMode", Symbol("oom_exit_code")=>"Int64", Symbol("sigkill_headroom_seconds")=>"Int64", Symbol("sigterm_lead_seconds")=>"Int64", Symbol("srun_mpi")=>"String", Symbol("srun_termination_signal")=>"String", Symbol("staggered_start")=>"Bool", Symbol("stdio")=>"StdioConfig", Symbol("termination_signal")=>"String", Symbol("timeout_exit_code")=>"Int64", )
OpenAPI.property_type(::Type{ ExecutionConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ExecutionConfig[name]))}

function OpenAPI.check_required(o::ExecutionConfig)
    true
end

function OpenAPI.validate_properties(o::ExecutionConfig)
    OpenAPI.validate_property(ExecutionConfig, Symbol("enable_cpu_bind"), o.enable_cpu_bind)
    OpenAPI.validate_property(ExecutionConfig, Symbol("job_stdio_overrides"), o.job_stdio_overrides)
    OpenAPI.validate_property(ExecutionConfig, Symbol("limit_resources"), o.limit_resources)
    OpenAPI.validate_property(ExecutionConfig, Symbol("mode"), o.mode)
    OpenAPI.validate_property(ExecutionConfig, Symbol("oom_exit_code"), o.oom_exit_code)
    OpenAPI.validate_property(ExecutionConfig, Symbol("sigkill_headroom_seconds"), o.sigkill_headroom_seconds)
    OpenAPI.validate_property(ExecutionConfig, Symbol("sigterm_lead_seconds"), o.sigterm_lead_seconds)
    OpenAPI.validate_property(ExecutionConfig, Symbol("srun_mpi"), o.srun_mpi)
    OpenAPI.validate_property(ExecutionConfig, Symbol("srun_termination_signal"), o.srun_termination_signal)
    OpenAPI.validate_property(ExecutionConfig, Symbol("staggered_start"), o.staggered_start)
    OpenAPI.validate_property(ExecutionConfig, Symbol("stdio"), o.stdio)
    OpenAPI.validate_property(ExecutionConfig, Symbol("termination_signal"), o.termination_signal)
    OpenAPI.validate_property(ExecutionConfig, Symbol("timeout_exit_code"), o.timeout_exit_code)
end

function OpenAPI.validate_property(::Type{ ExecutionConfig }, name::Symbol, val)





    if name === Symbol("oom_exit_code")
        OpenAPI.validate_param(name, "ExecutionConfig", :format, val, "int32")
    end

    if name === Symbol("sigkill_headroom_seconds")
        OpenAPI.validate_param(name, "ExecutionConfig", :format, val, "int64")
    end

    if name === Symbol("sigterm_lead_seconds")
        OpenAPI.validate_param(name, "ExecutionConfig", :format, val, "int64")
    end






    if name === Symbol("timeout_exit_code")
        OpenAPI.validate_param(name, "ExecutionConfig", :format, val, "int32")
    end
end
