# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SpawnJobsResponse

    SpawnJobsResponse(;
        iteration=nothing,
        spawned_job_ids=nothing,
    )

    - iteration::Int64 : This lineage&#39;s spawn-iteration counter after the call.
    - spawned_job_ids::Vector{Int64} : IDs of the jobs that were added (empty on a replay or final-state call).
"""
Base.@kwdef mutable struct SpawnJobsResponse <: OpenAPI.APIModel
    iteration::Union{Nothing, Int64} = nothing
    spawned_job_ids::Union{Nothing, Vector{Int64}} = nothing

    function SpawnJobsResponse(iteration, spawned_job_ids, )
        o = new(iteration, spawned_job_ids, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SpawnJobsResponse

const _property_types_SpawnJobsResponse = Dict{Symbol,String}(Symbol("iteration")=>"Int64", Symbol("spawned_job_ids")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ SpawnJobsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SpawnJobsResponse[name]))}

function OpenAPI.check_required(o::SpawnJobsResponse)
    o.iteration === nothing && (return false)
    o.spawned_job_ids === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SpawnJobsResponse)
    OpenAPI.validate_property(SpawnJobsResponse, Symbol("iteration"), o.iteration)
    OpenAPI.validate_property(SpawnJobsResponse, Symbol("spawned_job_ids"), o.spawned_job_ids)
end

function OpenAPI.validate_property(::Type{ SpawnJobsResponse }, name::Symbol, val)

    if name === Symbol("iteration")
        OpenAPI.validate_param(name, "SpawnJobsResponse", :format, val, "int64")
    end

end
