# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ComputeNodeMonitorConfig
Configuration for compute-node resource monitoring.

    ComputeNodeMonitorConfig(;
        cpu=true,
        enabled=false,
        granularity=nothing,
        memory=true,
    )

    - cpu::Bool
    - enabled::Bool
    - granularity::MonitorGranularity
    - memory::Bool
"""
Base.@kwdef mutable struct ComputeNodeMonitorConfig <: OpenAPI.APIModel
    cpu::Union{Nothing, Bool} = true
    enabled::Union{Nothing, Bool} = false
    granularity = nothing # spec type: Union{ Nothing, MonitorGranularity }
    memory::Union{Nothing, Bool} = true

    function ComputeNodeMonitorConfig(cpu, enabled, granularity, memory, )
        o = new(cpu, enabled, granularity, memory, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ComputeNodeMonitorConfig

const _property_types_ComputeNodeMonitorConfig = Dict{Symbol,String}(Symbol("cpu")=>"Bool", Symbol("enabled")=>"Bool", Symbol("granularity")=>"MonitorGranularity", Symbol("memory")=>"Bool", )
OpenAPI.property_type(::Type{ ComputeNodeMonitorConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ComputeNodeMonitorConfig[name]))}

function OpenAPI.check_required(o::ComputeNodeMonitorConfig)
    true
end

function OpenAPI.validate_properties(o::ComputeNodeMonitorConfig)
    OpenAPI.validate_property(ComputeNodeMonitorConfig, Symbol("cpu"), o.cpu)
    OpenAPI.validate_property(ComputeNodeMonitorConfig, Symbol("enabled"), o.enabled)
    OpenAPI.validate_property(ComputeNodeMonitorConfig, Symbol("granularity"), o.granularity)
    OpenAPI.validate_property(ComputeNodeMonitorConfig, Symbol("memory"), o.memory)
end

function OpenAPI.validate_property(::Type{ ComputeNodeMonitorConfig }, name::Symbol, val)




end
