# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""JobMonitorConfig
Configuration for per-job resource monitoring.

    JobMonitorConfig(;
        enabled=false,
        granularity=nothing,
    )

    - enabled::Bool
    - granularity::MonitorGranularity
"""
Base.@kwdef mutable struct JobMonitorConfig <: OpenAPI.APIModel
    enabled::Union{Nothing, Bool} = false
    granularity = nothing # spec type: Union{ Nothing, MonitorGranularity }

    function JobMonitorConfig(enabled, granularity, )
        o = new(enabled, granularity, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type JobMonitorConfig

const _property_types_JobMonitorConfig = Dict{Symbol,String}(Symbol("enabled")=>"Bool", Symbol("granularity")=>"MonitorGranularity", )
OpenAPI.property_type(::Type{ JobMonitorConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobMonitorConfig[name]))}

function OpenAPI.check_required(o::JobMonitorConfig)
    true
end

function OpenAPI.validate_properties(o::JobMonitorConfig)
    OpenAPI.validate_property(JobMonitorConfig, Symbol("enabled"), o.enabled)
    OpenAPI.validate_property(JobMonitorConfig, Symbol("granularity"), o.granularity)
end

function OpenAPI.validate_property(::Type{ JobMonitorConfig }, name::Symbol, val)


end
