# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateUserDataListResponse

    CreateUserDataListResponse(;
        user_data=nothing,
    )

    - user_data::Vector{UserDataModel}
"""
Base.@kwdef mutable struct CreateUserDataListResponse <: OpenAPI.APIModel
    user_data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{UserDataModel} }

    function CreateUserDataListResponse(user_data, )
        o = new(user_data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CreateUserDataListResponse

const _property_types_CreateUserDataListResponse = Dict{Symbol,String}(Symbol("user_data")=>"Vector{UserDataModel}", )
OpenAPI.property_type(::Type{ CreateUserDataListResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateUserDataListResponse[name]))}

function OpenAPI.check_required(o::CreateUserDataListResponse)
    true
end

function OpenAPI.validate_properties(o::CreateUserDataListResponse)
    OpenAPI.validate_property(CreateUserDataListResponse, Symbol("user_data"), o.user_data)
end

function OpenAPI.validate_property(::Type{ CreateUserDataListResponse }, name::Symbol, val)

end
