# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SlurmJobCorrelationsResponse
All Slurm-job-to-Torc-job correlations for a workflow, computed server-side.

    SlurmJobCorrelationsResponse(;
        items=nothing,
    )

    - items::Vector{SlurmJobCorrelationModel}
"""
Base.@kwdef mutable struct SlurmJobCorrelationsResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SlurmJobCorrelationModel} }

    function SlurmJobCorrelationsResponse(items, )
        o = new(items, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SlurmJobCorrelationsResponse

const _property_types_SlurmJobCorrelationsResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{SlurmJobCorrelationModel}", )
OpenAPI.property_type(::Type{ SlurmJobCorrelationsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SlurmJobCorrelationsResponse[name]))}

function OpenAPI.check_required(o::SlurmJobCorrelationsResponse)
    o.items === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SlurmJobCorrelationsResponse)
    OpenAPI.validate_property(SlurmJobCorrelationsResponse, Symbol("items"), o.items)
end

function OpenAPI.validate_property(::Type{ SlurmJobCorrelationsResponse }, name::Symbol, val)

end
