# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AdminSqlResponse
Response body for the admin raw-SQL endpoint (&#x60;POST /admin/sql&#x60;).

    AdminSqlResponse(;
        columns=nothing,
        committed=nothing,
        rows=nothing,
        rows_affected=nothing,
    )

    - columns::Vector{String} : Column names for SELECT results (empty for write statements).
    - committed::Bool : True when a write was committed to the database.
    - rows::Vector{Vector{Any}} : Result rows; each row is a list of JSON-encoded cell values aligned with &#x60;columns&#x60;.
    - rows_affected::Int64 : Number of rows affected by a write statement, when applicable.
"""
Base.@kwdef mutable struct AdminSqlResponse <: OpenAPI.APIModel
    columns::Union{Nothing, Vector{String}} = nothing
    committed::Union{Nothing, Bool} = nothing
    rows::Union{Nothing, Vector{Vector{Any}}} = nothing
    rows_affected::Union{Nothing, Int64} = nothing

    function AdminSqlResponse(columns, committed, rows, rows_affected, )
        o = new(columns, committed, rows, rows_affected, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AdminSqlResponse

const _property_types_AdminSqlResponse = Dict{Symbol,String}(Symbol("columns")=>"Vector{String}", Symbol("committed")=>"Bool", Symbol("rows")=>"Vector{Vector{Any}}", Symbol("rows_affected")=>"Int64", )
OpenAPI.property_type(::Type{ AdminSqlResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminSqlResponse[name]))}

function OpenAPI.check_required(o::AdminSqlResponse)
    o.columns === nothing && (return false)
    o.committed === nothing && (return false)
    o.rows === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AdminSqlResponse)
    OpenAPI.validate_property(AdminSqlResponse, Symbol("columns"), o.columns)
    OpenAPI.validate_property(AdminSqlResponse, Symbol("committed"), o.committed)
    OpenAPI.validate_property(AdminSqlResponse, Symbol("rows"), o.rows)
    OpenAPI.validate_property(AdminSqlResponse, Symbol("rows_affected"), o.rows_affected)
end

function OpenAPI.validate_property(::Type{ AdminSqlResponse }, name::Symbol, val)




    if name === Symbol("rows_affected")
        OpenAPI.validate_param(name, "AdminSqlResponse", :format, val, "int64")
    end
end
