# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ResourceMonitorConfig
Configuration for resource monitoring.  Used both as the user-authored &#x60;WorkflowSpec.resource_monitor&#x60; and as the persisted &#x60;WorkflowModel.resource_monitor_config&#x60; (stored as JSON in the &#x60;workflow.resource_monitor_config&#x60; column).

    ResourceMonitorConfig(;
        compute_node=nothing,
        enabled=false,
        flush_interval_seconds=300,
        generate_plots=false,
        granularity=nothing,
        jobs=nothing,
        sample_interval_seconds=10,
    )

    - compute_node::ComputeNodeMonitorConfig
    - enabled::Bool : Deprecated compatibility field. Use &#x60;jobs.enabled&#x60; for new workflow specs.
    - flush_interval_seconds::Int64 : How often buffered time-series samples are flushed to SQLite, in seconds.
    - generate_plots::Bool
    - granularity::MonitorGranularity : Deprecated compatibility field. Use &#x60;jobs.granularity&#x60; for new workflow specs.
    - jobs::JobMonitorConfig
    - sample_interval_seconds::Int64
"""
Base.@kwdef mutable struct ResourceMonitorConfig <: OpenAPI.APIModel
    compute_node = nothing # spec type: Union{ Nothing, ComputeNodeMonitorConfig }
    enabled::Union{Nothing, Bool} = false
    flush_interval_seconds::Union{Nothing, Int64} = 300
    generate_plots::Union{Nothing, Bool} = false
    granularity = nothing # spec type: Union{ Nothing, MonitorGranularity }
    jobs = nothing # spec type: Union{ Nothing, JobMonitorConfig }
    sample_interval_seconds::Union{Nothing, Int64} = 10

    function ResourceMonitorConfig(compute_node, enabled, flush_interval_seconds, generate_plots, granularity, jobs, sample_interval_seconds, )
        o = new(compute_node, enabled, flush_interval_seconds, generate_plots, granularity, jobs, sample_interval_seconds, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ResourceMonitorConfig

const _property_types_ResourceMonitorConfig = Dict{Symbol,String}(Symbol("compute_node")=>"ComputeNodeMonitorConfig", Symbol("enabled")=>"Bool", Symbol("flush_interval_seconds")=>"Int64", Symbol("generate_plots")=>"Bool", Symbol("granularity")=>"MonitorGranularity", Symbol("jobs")=>"JobMonitorConfig", Symbol("sample_interval_seconds")=>"Int64", )
OpenAPI.property_type(::Type{ ResourceMonitorConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResourceMonitorConfig[name]))}

function OpenAPI.check_required(o::ResourceMonitorConfig)
    true
end

function OpenAPI.validate_properties(o::ResourceMonitorConfig)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("compute_node"), o.compute_node)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("enabled"), o.enabled)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("flush_interval_seconds"), o.flush_interval_seconds)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("generate_plots"), o.generate_plots)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("granularity"), o.granularity)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("jobs"), o.jobs)
    OpenAPI.validate_property(ResourceMonitorConfig, Symbol("sample_interval_seconds"), o.sample_interval_seconds)
end

function OpenAPI.validate_property(::Type{ ResourceMonitorConfig }, name::Symbol, val)



    if name === Symbol("flush_interval_seconds")
        OpenAPI.validate_param(name, "ResourceMonitorConfig", :format, val, "int32")
    end




    if name === Symbol("sample_interval_seconds")
        OpenAPI.validate_param(name, "ResourceMonitorConfig", :format, val, "int32")
    end
end
