# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateFilesResponse

    CreateFilesResponse(;
        files=nothing,
    )

    - files::Vector{FileModel}
"""
Base.@kwdef mutable struct CreateFilesResponse <: OpenAPI.APIModel
    files::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FileModel} }

    function CreateFilesResponse(files, )
        o = new(files, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CreateFilesResponse

const _property_types_CreateFilesResponse = Dict{Symbol,String}(Symbol("files")=>"Vector{FileModel}", )
OpenAPI.property_type(::Type{ CreateFilesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateFilesResponse[name]))}

function OpenAPI.check_required(o::CreateFilesResponse)
    true
end

function OpenAPI.validate_properties(o::CreateFilesResponse)
    OpenAPI.validate_property(CreateFilesResponse, Symbol("files"), o.files)
end

function OpenAPI.validate_property(::Type{ CreateFilesResponse }, name::Symbol, val)

end
