# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""JobStatusCounts
Counts of jobs grouped by status for a single workflow.

    JobStatusCounts(;
        blocked=nothing,
        canceled=nothing,
        completed=nothing,
        disabled=nothing,
        failed=nothing,
        pending=nothing,
        pending_failed=nothing,
        ready=nothing,
        running=nothing,
        terminated=nothing,
        uninitialized=nothing,
    )

    - blocked::Int64
    - canceled::Int64
    - completed::Int64
    - disabled::Int64
    - failed::Int64
    - pending::Int64
    - pending_failed::Int64
    - ready::Int64
    - running::Int64
    - terminated::Int64
    - uninitialized::Int64
"""
Base.@kwdef mutable struct JobStatusCounts <: OpenAPI.APIModel
    blocked::Union{Nothing, Int64} = nothing
    canceled::Union{Nothing, Int64} = nothing
    completed::Union{Nothing, Int64} = nothing
    disabled::Union{Nothing, Int64} = nothing
    failed::Union{Nothing, Int64} = nothing
    pending::Union{Nothing, Int64} = nothing
    pending_failed::Union{Nothing, Int64} = nothing
    ready::Union{Nothing, Int64} = nothing
    running::Union{Nothing, Int64} = nothing
    terminated::Union{Nothing, Int64} = nothing
    uninitialized::Union{Nothing, Int64} = nothing

    function JobStatusCounts(blocked, canceled, completed, disabled, failed, pending, pending_failed, ready, running, terminated, uninitialized, )
        o = new(blocked, canceled, completed, disabled, failed, pending, pending_failed, ready, running, terminated, uninitialized, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type JobStatusCounts

const _property_types_JobStatusCounts = Dict{Symbol,String}(Symbol("blocked")=>"Int64", Symbol("canceled")=>"Int64", Symbol("completed")=>"Int64", Symbol("disabled")=>"Int64", Symbol("failed")=>"Int64", Symbol("pending")=>"Int64", Symbol("pending_failed")=>"Int64", Symbol("ready")=>"Int64", Symbol("running")=>"Int64", Symbol("terminated")=>"Int64", Symbol("uninitialized")=>"Int64", )
OpenAPI.property_type(::Type{ JobStatusCounts }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobStatusCounts[name]))}

function OpenAPI.check_required(o::JobStatusCounts)
    o.blocked === nothing && (return false)
    o.canceled === nothing && (return false)
    o.completed === nothing && (return false)
    o.disabled === nothing && (return false)
    o.failed === nothing && (return false)
    o.pending === nothing && (return false)
    o.pending_failed === nothing && (return false)
    o.ready === nothing && (return false)
    o.running === nothing && (return false)
    o.terminated === nothing && (return false)
    o.uninitialized === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::JobStatusCounts)
    OpenAPI.validate_property(JobStatusCounts, Symbol("blocked"), o.blocked)
    OpenAPI.validate_property(JobStatusCounts, Symbol("canceled"), o.canceled)
    OpenAPI.validate_property(JobStatusCounts, Symbol("completed"), o.completed)
    OpenAPI.validate_property(JobStatusCounts, Symbol("disabled"), o.disabled)
    OpenAPI.validate_property(JobStatusCounts, Symbol("failed"), o.failed)
    OpenAPI.validate_property(JobStatusCounts, Symbol("pending"), o.pending)
    OpenAPI.validate_property(JobStatusCounts, Symbol("pending_failed"), o.pending_failed)
    OpenAPI.validate_property(JobStatusCounts, Symbol("ready"), o.ready)
    OpenAPI.validate_property(JobStatusCounts, Symbol("running"), o.running)
    OpenAPI.validate_property(JobStatusCounts, Symbol("terminated"), o.terminated)
    OpenAPI.validate_property(JobStatusCounts, Symbol("uninitialized"), o.uninitialized)
end

function OpenAPI.validate_property(::Type{ JobStatusCounts }, name::Symbol, val)

    if name === Symbol("blocked")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("canceled")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("completed")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("disabled")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("failed")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("pending")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("pending_failed")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("ready")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("running")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("terminated")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end

    if name === Symbol("uninitialized")
        OpenAPI.validate_param(name, "JobStatusCounts", :format, val, "int64")
    end
end
