# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DynamicJobsConfig
Dynamic job spawning configuration. Used both as the user-authored &#x60;WorkflowSpec.dynamic_jobs&#x60; and as the persisted &#x60;WorkflowModel.dynamic_jobs&#x60; (stored as JSON in the &#x60;workflow.dynamic_jobs&#x60; column). Runtime-immutable.

    DynamicJobsConfig(;
        max_iterations=nothing,
    )

    - max_iterations::Int64 : Cap on &#x60;spawn_jobs&#x60; calls per orchestrator lineage. &#x60;None&#x60; applies the server default.
"""
Base.@kwdef mutable struct DynamicJobsConfig <: OpenAPI.APIModel
    max_iterations::Union{Nothing, Int64} = nothing

    function DynamicJobsConfig(max_iterations, )
        o = new(max_iterations, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DynamicJobsConfig

const _property_types_DynamicJobsConfig = Dict{Symbol,String}(Symbol("max_iterations")=>"Int64", )
OpenAPI.property_type(::Type{ DynamicJobsConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DynamicJobsConfig[name]))}

function OpenAPI.check_required(o::DynamicJobsConfig)
    true
end

function OpenAPI.validate_properties(o::DynamicJobsConfig)
    OpenAPI.validate_property(DynamicJobsConfig, Symbol("max_iterations"), o.max_iterations)
end

function OpenAPI.validate_property(::Type{ DynamicJobsConfig }, name::Symbol, val)

    if name === Symbol("max_iterations")
        OpenAPI.validate_param(name, "DynamicJobsConfig", :format, val, "int64")
    end
end
