# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AdminSqlRequest
Request body for the admin raw-SQL endpoint (&#x60;POST /admin/sql&#x60;).

    AdminSqlRequest(;
        allow_full_table=nothing,
        dry_run=nothing,
        limit=nothing,
        sql=nothing,
        write=nothing,
    )

    - allow_full_table::Bool : Permit an unqualified UPDATE/DELETE (no WHERE clause). Ignored on the read-only path.
    - dry_run::Bool : Write path only: run inside a transaction, report rows affected, then roll back instead of committing (preview).
    - limit::Int64 : Maximum number of SELECT result rows to return. Defaults to and is capped at 100,000 (the server-wide list cap); values above the cap are clamped.
    - sql::String : The single SQL statement to execute.
    - write::Bool : Opt into the write path. When false (default) the statement runs on a read-only connection, so any write fails at the SQLite layer.
"""
Base.@kwdef mutable struct AdminSqlRequest <: OpenAPI.APIModel
    allow_full_table::Union{Nothing, Bool} = nothing
    dry_run::Union{Nothing, Bool} = nothing
    limit::Union{Nothing, Int64} = nothing
    sql::Union{Nothing, String} = nothing
    write::Union{Nothing, Bool} = nothing

    function AdminSqlRequest(allow_full_table, dry_run, limit, sql, write, )
        o = new(allow_full_table, dry_run, limit, sql, write, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AdminSqlRequest

const _property_types_AdminSqlRequest = Dict{Symbol,String}(Symbol("allow_full_table")=>"Bool", Symbol("dry_run")=>"Bool", Symbol("limit")=>"Int64", Symbol("sql")=>"String", Symbol("write")=>"Bool", )
OpenAPI.property_type(::Type{ AdminSqlRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminSqlRequest[name]))}

function OpenAPI.check_required(o::AdminSqlRequest)
    o.sql === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AdminSqlRequest)
    OpenAPI.validate_property(AdminSqlRequest, Symbol("allow_full_table"), o.allow_full_table)
    OpenAPI.validate_property(AdminSqlRequest, Symbol("dry_run"), o.dry_run)
    OpenAPI.validate_property(AdminSqlRequest, Symbol("limit"), o.limit)
    OpenAPI.validate_property(AdminSqlRequest, Symbol("sql"), o.sql)
    OpenAPI.validate_property(AdminSqlRequest, Symbol("write"), o.write)
end

function OpenAPI.validate_property(::Type{ AdminSqlRequest }, name::Symbol, val)



    if name === Symbol("limit")
        OpenAPI.validate_param(name, "AdminSqlRequest", :format, val, "int64")
    end


end
