# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WorkflowStatusResponse
Aggregated status summary for a workflow, computed server-side.

    WorkflowStatusResponse(;
        active_compute_nodes=nothing,
        active_scheduled_nodes=nothing,
        is_canceled=nothing,
        is_complete=nothing,
        jobs_by_status=nothing,
        longest_ready_runtime_seconds=nothing,
        max_allocation_remaining_seconds=nothing,
        pending_scheduled_nodes=nothing,
        runtime_blocked_ready_jobs=nothing,
        total_exec_time_minutes=nothing,
        total_jobs=nothing,
        walltime_seconds=nothing,
        workflow_id=nothing,
        workflow_name=nothing,
        workflow_user=nothing,
    )

    - active_compute_nodes::Int64
    - active_scheduled_nodes::Int64
    - is_canceled::Bool
    - is_complete::Bool
    - jobs_by_status::JobStatusCounts
    - longest_ready_runtime_seconds::Int64 : Longest required runtime (seconds) among ready jobs. Only populated when some ready jobs are runtime-blocked.
    - max_allocation_remaining_seconds::Int64 : Greatest remaining walltime (seconds) across active walltime-bounded allocations. None when no active allocation reports an end time.
    - pending_scheduled_nodes::Int64
    - runtime_blocked_ready_jobs::Int64 : Ready jobs whose required runtime exceeds the remaining walltime of every active allocation, so they cannot start until a fresh allocation appears. 0 when there are no walltime-bounded allocations. See &#x60;torc workflows diagnose&#x60;.
    - total_exec_time_minutes::Float64
    - total_jobs::Int64
    - walltime_seconds::Float64
    - workflow_id::Int64
    - workflow_name::String
    - workflow_user::String
"""
Base.@kwdef mutable struct WorkflowStatusResponse <: OpenAPI.APIModel
    active_compute_nodes::Union{Nothing, Int64} = nothing
    active_scheduled_nodes::Union{Nothing, Int64} = nothing
    is_canceled::Union{Nothing, Bool} = nothing
    is_complete::Union{Nothing, Bool} = nothing
    jobs_by_status = nothing # spec type: Union{ Nothing, JobStatusCounts }
    longest_ready_runtime_seconds::Union{Nothing, Int64} = nothing
    max_allocation_remaining_seconds::Union{Nothing, Int64} = nothing
    pending_scheduled_nodes::Union{Nothing, Int64} = nothing
    runtime_blocked_ready_jobs::Union{Nothing, Int64} = nothing
    total_exec_time_minutes::Union{Nothing, Float64} = nothing
    total_jobs::Union{Nothing, Int64} = nothing
    walltime_seconds::Union{Nothing, Float64} = nothing
    workflow_id::Union{Nothing, Int64} = nothing
    workflow_name::Union{Nothing, String} = nothing
    workflow_user::Union{Nothing, String} = nothing

    function WorkflowStatusResponse(active_compute_nodes, active_scheduled_nodes, is_canceled, is_complete, jobs_by_status, longest_ready_runtime_seconds, max_allocation_remaining_seconds, pending_scheduled_nodes, runtime_blocked_ready_jobs, total_exec_time_minutes, total_jobs, walltime_seconds, workflow_id, workflow_name, workflow_user, )
        o = new(active_compute_nodes, active_scheduled_nodes, is_canceled, is_complete, jobs_by_status, longest_ready_runtime_seconds, max_allocation_remaining_seconds, pending_scheduled_nodes, runtime_blocked_ready_jobs, total_exec_time_minutes, total_jobs, walltime_seconds, workflow_id, workflow_name, workflow_user, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type WorkflowStatusResponse

const _property_types_WorkflowStatusResponse = Dict{Symbol,String}(Symbol("active_compute_nodes")=>"Int64", Symbol("active_scheduled_nodes")=>"Int64", Symbol("is_canceled")=>"Bool", Symbol("is_complete")=>"Bool", Symbol("jobs_by_status")=>"JobStatusCounts", Symbol("longest_ready_runtime_seconds")=>"Int64", Symbol("max_allocation_remaining_seconds")=>"Int64", Symbol("pending_scheduled_nodes")=>"Int64", Symbol("runtime_blocked_ready_jobs")=>"Int64", Symbol("total_exec_time_minutes")=>"Float64", Symbol("total_jobs")=>"Int64", Symbol("walltime_seconds")=>"Float64", Symbol("workflow_id")=>"Int64", Symbol("workflow_name")=>"String", Symbol("workflow_user")=>"String", )
OpenAPI.property_type(::Type{ WorkflowStatusResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowStatusResponse[name]))}

function OpenAPI.check_required(o::WorkflowStatusResponse)
    o.active_compute_nodes === nothing && (return false)
    o.active_scheduled_nodes === nothing && (return false)
    o.is_canceled === nothing && (return false)
    o.is_complete === nothing && (return false)
    o.jobs_by_status === nothing && (return false)
    o.pending_scheduled_nodes === nothing && (return false)
    o.runtime_blocked_ready_jobs === nothing && (return false)
    o.total_exec_time_minutes === nothing && (return false)
    o.total_jobs === nothing && (return false)
    o.workflow_id === nothing && (return false)
    o.workflow_name === nothing && (return false)
    o.workflow_user === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::WorkflowStatusResponse)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("active_compute_nodes"), o.active_compute_nodes)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("active_scheduled_nodes"), o.active_scheduled_nodes)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("is_canceled"), o.is_canceled)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("is_complete"), o.is_complete)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("jobs_by_status"), o.jobs_by_status)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("longest_ready_runtime_seconds"), o.longest_ready_runtime_seconds)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("max_allocation_remaining_seconds"), o.max_allocation_remaining_seconds)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("pending_scheduled_nodes"), o.pending_scheduled_nodes)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("runtime_blocked_ready_jobs"), o.runtime_blocked_ready_jobs)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("total_exec_time_minutes"), o.total_exec_time_minutes)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("total_jobs"), o.total_jobs)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("walltime_seconds"), o.walltime_seconds)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("workflow_id"), o.workflow_id)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("workflow_name"), o.workflow_name)
    OpenAPI.validate_property(WorkflowStatusResponse, Symbol("workflow_user"), o.workflow_user)
end

function OpenAPI.validate_property(::Type{ WorkflowStatusResponse }, name::Symbol, val)

    if name === Symbol("active_compute_nodes")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end

    if name === Symbol("active_scheduled_nodes")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end




    if name === Symbol("longest_ready_runtime_seconds")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end

    if name === Symbol("max_allocation_remaining_seconds")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end

    if name === Symbol("pending_scheduled_nodes")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end

    if name === Symbol("runtime_blocked_ready_jobs")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end

    if name === Symbol("total_exec_time_minutes")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "double")
    end

    if name === Symbol("total_jobs")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end

    if name === Symbol("walltime_seconds")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "double")
    end

    if name === Symbol("workflow_id")
        OpenAPI.validate_param(name, "WorkflowStatusResponse", :format, val, "int64")
    end


end
