# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WorkflowModel

    WorkflowModel(;
        access_groups=nothing,
        compute_node_expiration_buffer_seconds=nothing,
        compute_node_ignore_workflow_completion=nothing,
        compute_node_min_time_for_new_jobs_seconds=nothing,
        compute_node_wait_for_healthy_database_minutes=nothing,
        compute_node_wait_for_new_jobs_seconds=nothing,
        description=nothing,
        dynamic_jobs=nothing,
        enable_ro_crate=nothing,
        env=nothing,
        execution_config=nothing,
        id=nothing,
        is_archived=nothing,
        is_canceled=nothing,
        metadata=nothing,
        name=nothing,
        project=nothing,
        resource_monitor_config=nothing,
        run_id=nothing,
        slurm_defaults=nothing,
        submission_directory=nothing,
        timestamp=nothing,
        use_pending_failed=nothing,
        user=nothing,
    )

    - access_groups::Vector{String} : Access group names granted shared access to this workflow. Projection of the &#x60;workflow_access_group&#x60; join table (which remains the source of truth). On create, names are resolved to group IDs and join rows are inserted in the same transaction as the workflow row; an unknown name fails the whole create. On read, populated from the join table. Use &#x60;add_workflow_to_group&#x60; / &#x60;remove_workflow_from_group&#x60; for post-creation changes.
    - compute_node_expiration_buffer_seconds::Int64
    - compute_node_ignore_workflow_completion::Bool
    - compute_node_min_time_for_new_jobs_seconds::Int64
    - compute_node_wait_for_healthy_database_minutes::Int64
    - compute_node_wait_for_new_jobs_seconds::Int64
    - description::String
    - dynamic_jobs::DynamicJobsConfig : Dynamic job spawning configuration. Mirrors the workflow-spec &#x60;dynamic_jobs&#x60; section identically. Runtime-immutable after workflow creation.
    - enable_ro_crate::Bool
    - env::Dict{String, String}
    - execution_config::ExecutionConfig
    - id::Int64
    - is_archived::Bool : True when the workflow has been archived. Read-only on the API: set via &#x60;POST /workflows/{id}/archive&#x60;, cleared via &#x60;POST /workflows/{id}/reset_status&#x60;. Values supplied to create/update workflow endpoints are ignored.
    - is_canceled::Bool : True when a user (or scheduler) has canceled the workflow. Read-only on the API: set via &#x60;POST /workflows/{id}/cancel&#x60;, cleared via &#x60;POST /workflows/{id}/reset_status&#x60;. Values supplied to create/update workflow endpoints are ignored.
    - metadata::Dict{String, Any}
    - name::String
    - project::String
    - resource_monitor_config::ResourceMonitorConfig
    - run_id::Int64 : Current run number; incremented on each restart/recovery. Read-only on the API: incremented as a side effect of &#x60;POST /workflows/{id}/reset_status&#x60;. Values supplied to create/update workflow endpoints are ignored.
    - slurm_defaults::Dict{String, Any}
    - submission_directory::String : Absolute directory the workflow was originally submitted from (captured at &#x60;torc create&#x60; / &#x60;torc run&#x60; / &#x60;torc submit&#x60; time). Exposed to jobs as &#x60;TORC_WORKFLOW_SUBMISSION_DIR&#x60; so user code with relative paths can resolve against the original CWD even when run on a compute node. Set once at workflow creation and not overwritten by later &#x60;schedule-nodes&#x60;/&#x60;watch&#x60; invocations.
    - timestamp::String
    - use_pending_failed::Bool
    - user::String
"""
Base.@kwdef mutable struct WorkflowModel <: OpenAPI.APIModel
    access_groups::Union{Nothing, Vector{String}} = nothing
    compute_node_expiration_buffer_seconds::Union{Nothing, Int64} = nothing
    compute_node_ignore_workflow_completion::Union{Nothing, Bool} = nothing
    compute_node_min_time_for_new_jobs_seconds::Union{Nothing, Int64} = nothing
    compute_node_wait_for_healthy_database_minutes::Union{Nothing, Int64} = nothing
    compute_node_wait_for_new_jobs_seconds::Union{Nothing, Int64} = nothing
    description::Union{Nothing, String} = nothing
    dynamic_jobs = nothing # spec type: Union{ Nothing, DynamicJobsConfig }
    enable_ro_crate::Union{Nothing, Bool} = nothing
    env::Union{Nothing, Dict{String, String}} = nothing
    execution_config = nothing # spec type: Union{ Nothing, ExecutionConfig }
    id::Union{Nothing, Int64} = nothing
    is_archived::Union{Nothing, Bool} = nothing
    is_canceled::Union{Nothing, Bool} = nothing
    metadata::Union{Nothing, Dict{String, Any}} = nothing
    name::Union{Nothing, String} = nothing
    project::Union{Nothing, String} = nothing
    resource_monitor_config = nothing # spec type: Union{ Nothing, ResourceMonitorConfig }
    run_id::Union{Nothing, Int64} = nothing
    slurm_defaults::Union{Nothing, Dict{String, Any}} = nothing
    submission_directory::Union{Nothing, String} = nothing
    timestamp::Union{Nothing, String} = nothing
    use_pending_failed::Union{Nothing, Bool} = nothing
    user::Union{Nothing, String} = nothing

    function WorkflowModel(access_groups, compute_node_expiration_buffer_seconds, compute_node_ignore_workflow_completion, compute_node_min_time_for_new_jobs_seconds, compute_node_wait_for_healthy_database_minutes, compute_node_wait_for_new_jobs_seconds, description, dynamic_jobs, enable_ro_crate, env, execution_config, id, is_archived, is_canceled, metadata, name, project, resource_monitor_config, run_id, slurm_defaults, submission_directory, timestamp, use_pending_failed, user, )
        o = new(access_groups, compute_node_expiration_buffer_seconds, compute_node_ignore_workflow_completion, compute_node_min_time_for_new_jobs_seconds, compute_node_wait_for_healthy_database_minutes, compute_node_wait_for_new_jobs_seconds, description, dynamic_jobs, enable_ro_crate, env, execution_config, id, is_archived, is_canceled, metadata, name, project, resource_monitor_config, run_id, slurm_defaults, submission_directory, timestamp, use_pending_failed, user, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type WorkflowModel

const _property_types_WorkflowModel = Dict{Symbol,String}(Symbol("access_groups")=>"Vector{String}", Symbol("compute_node_expiration_buffer_seconds")=>"Int64", Symbol("compute_node_ignore_workflow_completion")=>"Bool", Symbol("compute_node_min_time_for_new_jobs_seconds")=>"Int64", Symbol("compute_node_wait_for_healthy_database_minutes")=>"Int64", Symbol("compute_node_wait_for_new_jobs_seconds")=>"Int64", Symbol("description")=>"String", Symbol("dynamic_jobs")=>"DynamicJobsConfig", Symbol("enable_ro_crate")=>"Bool", Symbol("env")=>"Dict{String, String}", Symbol("execution_config")=>"ExecutionConfig", Symbol("id")=>"Int64", Symbol("is_archived")=>"Bool", Symbol("is_canceled")=>"Bool", Symbol("metadata")=>"Dict{String, Any}", Symbol("name")=>"String", Symbol("project")=>"String", Symbol("resource_monitor_config")=>"ResourceMonitorConfig", Symbol("run_id")=>"Int64", Symbol("slurm_defaults")=>"Dict{String, Any}", Symbol("submission_directory")=>"String", Symbol("timestamp")=>"String", Symbol("use_pending_failed")=>"Bool", Symbol("user")=>"String", )
OpenAPI.property_type(::Type{ WorkflowModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowModel[name]))}

function OpenAPI.check_required(o::WorkflowModel)
    o.name === nothing && (return false)
    o.user === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::WorkflowModel)
    OpenAPI.validate_property(WorkflowModel, Symbol("access_groups"), o.access_groups)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_expiration_buffer_seconds"), o.compute_node_expiration_buffer_seconds)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_ignore_workflow_completion"), o.compute_node_ignore_workflow_completion)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_min_time_for_new_jobs_seconds"), o.compute_node_min_time_for_new_jobs_seconds)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_wait_for_healthy_database_minutes"), o.compute_node_wait_for_healthy_database_minutes)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_wait_for_new_jobs_seconds"), o.compute_node_wait_for_new_jobs_seconds)
    OpenAPI.validate_property(WorkflowModel, Symbol("description"), o.description)
    OpenAPI.validate_property(WorkflowModel, Symbol("dynamic_jobs"), o.dynamic_jobs)
    OpenAPI.validate_property(WorkflowModel, Symbol("enable_ro_crate"), o.enable_ro_crate)
    OpenAPI.validate_property(WorkflowModel, Symbol("env"), o.env)
    OpenAPI.validate_property(WorkflowModel, Symbol("execution_config"), o.execution_config)
    OpenAPI.validate_property(WorkflowModel, Symbol("id"), o.id)
    OpenAPI.validate_property(WorkflowModel, Symbol("is_archived"), o.is_archived)
    OpenAPI.validate_property(WorkflowModel, Symbol("is_canceled"), o.is_canceled)
    OpenAPI.validate_property(WorkflowModel, Symbol("metadata"), o.metadata)
    OpenAPI.validate_property(WorkflowModel, Symbol("name"), o.name)
    OpenAPI.validate_property(WorkflowModel, Symbol("project"), o.project)
    OpenAPI.validate_property(WorkflowModel, Symbol("resource_monitor_config"), o.resource_monitor_config)
    OpenAPI.validate_property(WorkflowModel, Symbol("run_id"), o.run_id)
    OpenAPI.validate_property(WorkflowModel, Symbol("slurm_defaults"), o.slurm_defaults)
    OpenAPI.validate_property(WorkflowModel, Symbol("submission_directory"), o.submission_directory)
    OpenAPI.validate_property(WorkflowModel, Symbol("timestamp"), o.timestamp)
    OpenAPI.validate_property(WorkflowModel, Symbol("use_pending_failed"), o.use_pending_failed)
    OpenAPI.validate_property(WorkflowModel, Symbol("user"), o.user)
end

function OpenAPI.validate_property(::Type{ WorkflowModel }, name::Symbol, val)


    if name === Symbol("compute_node_expiration_buffer_seconds")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end


    if name === Symbol("compute_node_min_time_for_new_jobs_seconds")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end

    if name === Symbol("compute_node_wait_for_healthy_database_minutes")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end

    if name === Symbol("compute_node_wait_for_new_jobs_seconds")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end






    if name === Symbol("id")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end







    if name === Symbol("run_id")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end





end
