# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :ExecutionMode)
    const ExecutionMode = String
else
    @warn("Skipping redefinition of ExecutionMode to String")
end
