# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UserDataListModel

    UserDataListModel(;
        user_data=nothing,
    )

    - user_data::Vector{UserDataModel}
"""
Base.@kwdef mutable struct UserDataListModel <: OpenAPI.APIModel
    user_data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{UserDataModel} }

    function UserDataListModel(user_data, )
        o = new(user_data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type UserDataListModel

const _property_types_UserDataListModel = Dict{Symbol,String}(Symbol("user_data")=>"Vector{UserDataModel}", )
OpenAPI.property_type(::Type{ UserDataListModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserDataListModel[name]))}

function OpenAPI.check_required(o::UserDataListModel)
    o.user_data === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::UserDataListModel)
    OpenAPI.validate_property(UserDataListModel, Symbol("user_data"), o.user_data)
end

function OpenAPI.validate_property(::Type{ UserDataListModel }, name::Symbol, val)

end
