# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StdioConfig
Configuration for job stdout/stderr capture.

    StdioConfig(;
        delete_on_success=nothing,
        mode=nothing,
    )

    - delete_on_success::Bool : Delete stdout/stderr files if the job completes successfully.
    - mode::StdioMode : How to capture stdout/stderr. Default: separate files.
"""
Base.@kwdef mutable struct StdioConfig <: OpenAPI.APIModel
    delete_on_success::Union{Nothing, Bool} = nothing
    mode = nothing # spec type: Union{ Nothing, StdioMode }

    function StdioConfig(delete_on_success, mode, )
        o = new(delete_on_success, mode, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type StdioConfig

const _property_types_StdioConfig = Dict{Symbol,String}(Symbol("delete_on_success")=>"Bool", Symbol("mode")=>"StdioMode", )
OpenAPI.property_type(::Type{ StdioConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StdioConfig[name]))}

function OpenAPI.check_required(o::StdioConfig)
    true
end

function OpenAPI.validate_properties(o::StdioConfig)
    OpenAPI.validate_property(StdioConfig, Symbol("delete_on_success"), o.delete_on_success)
    OpenAPI.validate_property(StdioConfig, Symbol("mode"), o.mode)
end

function OpenAPI.validate_property(::Type{ StdioConfig }, name::Symbol, val)


end
