# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SpawnJobModel
One job to add atomically as part of &#x60;spawn_jobs&#x60;.  &#x60;depends_on&#x60; entries may reference jobs that already exist in the workflow or sibling jobs created in the same request (resolved by name within the transaction). A job with no dependencies is created &#x60;ready&#x60;; one with dependencies is created &#x60;blocked&#x60; and promoted by the normal background unblock path once its dependencies are terminal.

    SpawnJobModel(;
        cancel_on_blocking_job_failure=nothing,
        command=nothing,
        depends_on=nothing,
        name=nothing,
        priority=nothing,
        resource_requirements=nothing,
    )

    - cancel_on_blocking_job_failure::Bool
    - command::String
    - depends_on::Vector{String} : Job names this job depends on (existing jobs or siblings in this batch).
    - name::String
    - priority::Int64
    - resource_requirements::String : Name of an existing resource_requirements record in the workflow.
"""
Base.@kwdef mutable struct SpawnJobModel <: OpenAPI.APIModel
    cancel_on_blocking_job_failure::Union{Nothing, Bool} = nothing
    command::Union{Nothing, String} = nothing
    depends_on::Union{Nothing, Vector{String}} = nothing
    name::Union{Nothing, String} = nothing
    priority::Union{Nothing, Int64} = nothing
    resource_requirements::Union{Nothing, String} = nothing

    function SpawnJobModel(cancel_on_blocking_job_failure, command, depends_on, name, priority, resource_requirements, )
        o = new(cancel_on_blocking_job_failure, command, depends_on, name, priority, resource_requirements, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SpawnJobModel

const _property_types_SpawnJobModel = Dict{Symbol,String}(Symbol("cancel_on_blocking_job_failure")=>"Bool", Symbol("command")=>"String", Symbol("depends_on")=>"Vector{String}", Symbol("name")=>"String", Symbol("priority")=>"Int64", Symbol("resource_requirements")=>"String", )
OpenAPI.property_type(::Type{ SpawnJobModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SpawnJobModel[name]))}

function OpenAPI.check_required(o::SpawnJobModel)
    o.command === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SpawnJobModel)
    OpenAPI.validate_property(SpawnJobModel, Symbol("cancel_on_blocking_job_failure"), o.cancel_on_blocking_job_failure)
    OpenAPI.validate_property(SpawnJobModel, Symbol("command"), o.command)
    OpenAPI.validate_property(SpawnJobModel, Symbol("depends_on"), o.depends_on)
    OpenAPI.validate_property(SpawnJobModel, Symbol("name"), o.name)
    OpenAPI.validate_property(SpawnJobModel, Symbol("priority"), o.priority)
    OpenAPI.validate_property(SpawnJobModel, Symbol("resource_requirements"), o.resource_requirements)
end

function OpenAPI.validate_property(::Type{ SpawnJobModel }, name::Symbol, val)





    if name === Symbol("priority")
        OpenAPI.validate_param(name, "SpawnJobModel", :format, val, "int64")
    end

end
