# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""dataset_finalization_request
Request body for finalizing a dataset.

    DatasetFinalizationRequest(;
        file_count=nothing,
        total_size_bytes=nothing,
        manifest_hash=nothing,
    )

    - file_count::Int64 : Number of files in the dataset.
    - total_size_bytes::Int64 : Total size of all files in bytes.
    - manifest_hash::String : Hash of the dataset contents (optional based on hash_mode).
"""
Base.@kwdef mutable struct DatasetFinalizationRequest <: OpenAPI.APIModel
    file_count::Union{Nothing, Int64} = nothing
    total_size_bytes::Union{Nothing, Int64} = nothing
    manifest_hash::Union{Nothing, String} = nothing

    function DatasetFinalizationRequest(file_count, total_size_bytes, manifest_hash, )
        o = new(file_count, total_size_bytes, manifest_hash, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DatasetFinalizationRequest

const _property_types_DatasetFinalizationRequest = Dict{Symbol,String}(Symbol("file_count")=>"Int64", Symbol("total_size_bytes")=>"Int64", Symbol("manifest_hash")=>"String", )
OpenAPI.property_type(::Type{ DatasetFinalizationRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DatasetFinalizationRequest[name]))}

function OpenAPI.check_required(o::DatasetFinalizationRequest)
    o.file_count === nothing && (return false)
    o.total_size_bytes === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DatasetFinalizationRequest)
    OpenAPI.validate_property(DatasetFinalizationRequest, Symbol("file_count"), o.file_count)
    OpenAPI.validate_property(DatasetFinalizationRequest, Symbol("total_size_bytes"), o.total_size_bytes)
    OpenAPI.validate_property(DatasetFinalizationRequest, Symbol("manifest_hash"), o.manifest_hash)
end

function OpenAPI.validate_property(::Type{ DatasetFinalizationRequest }, name::Symbol, val)



end
