# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SpawnJobsRequest
Add a batch of new jobs to an initialized workflow, all blocked on the calling job. The calling job is **not** completed by this call — the orchestrator script exits normally and the runner completes it, at which point the unblock cascade promotes the spawned jobs.  The per-lineage spawn-iteration counter is advanced and an opaque state payload is persisted, all in the same transaction as the inserts.

    SpawnJobsRequest(;
        jobs=nothing,
        lineage=nothing,
        state=nothing,
    )

    - jobs::Vector{SpawnJobModel} : Jobs to add. May be empty (record final state without spawning).
    - lineage::String : Orchestrator lineage identifier. Defaults to the calling job&#39;s name. The per-lineage spawn counter and state records are keyed on this.
    - state::Any : Opaque JSON state attached to this generation (or as the converged final state when &#x60;jobs&#x60; is empty).
"""
Base.@kwdef mutable struct SpawnJobsRequest <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SpawnJobModel} }
    lineage::Union{Nothing, String} = nothing
    state::Union{Nothing, Any} = nothing

    function SpawnJobsRequest(jobs, lineage, state, )
        o = new(jobs, lineage, state, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SpawnJobsRequest

const _property_types_SpawnJobsRequest = Dict{Symbol,String}(Symbol("jobs")=>"Vector{SpawnJobModel}", Symbol("lineage")=>"String", Symbol("state")=>"Any", )
OpenAPI.property_type(::Type{ SpawnJobsRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SpawnJobsRequest[name]))}

function OpenAPI.check_required(o::SpawnJobsRequest)
    o.jobs === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SpawnJobsRequest)
    OpenAPI.validate_property(SpawnJobsRequest, Symbol("jobs"), o.jobs)
    OpenAPI.validate_property(SpawnJobsRequest, Symbol("lineage"), o.lineage)
    OpenAPI.validate_property(SpawnJobsRequest, Symbol("state"), o.state)
end

function OpenAPI.validate_property(::Type{ SpawnJobsRequest }, name::Symbol, val)



end
