# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FilesModel

    FilesModel(;
        files=nothing,
    )

    - files::Vector{FileModel}
"""
Base.@kwdef mutable struct FilesModel <: OpenAPI.APIModel
    files::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FileModel} }

    function FilesModel(files, )
        o = new(files, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type FilesModel

const _property_types_FilesModel = Dict{Symbol,String}(Symbol("files")=>"Vector{FileModel}", )
OpenAPI.property_type(::Type{ FilesModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FilesModel[name]))}

function OpenAPI.check_required(o::FilesModel)
    o.files === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::FilesModel)
    OpenAPI.validate_property(FilesModel, Symbol("files"), o.files)
end

function OpenAPI.validate_property(::Type{ FilesModel }, name::Symbol, val)

end
