# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AdminAuditLogEntry
One row of the admin raw-SQL audit log (&#x60;admin_audit_log&#x60;), returned by &#x60;GET /admin/audit-log&#x60; (&#x60;torc admin list-audit-log&#x60;).

    AdminAuditLogEntry(;
        allow_full_table=nothing,
        committed=nothing,
        error=nothing,
        id=nothing,
        is_write=nothing,
        rows_affected=nothing,
        sql_text=nothing,
        success=nothing,
        timestamp=nothing,
        user_name=nothing,
    )

    - allow_full_table::Bool : True when the full-table guard was overridden for this statement.
    - committed::Bool : True when the write was committed to the database.
    - error::String : Error message captured for a failed statement, when applicable.
    - id::Int64 : Auto-increment row id.
    - is_write::Bool : True for write-path statements (all audited rows are writes).
    - rows_affected::Int64 : Rows affected by the statement, when known.
    - sql_text::String : The SQL statement text.
    - success::Bool : True when the statement executed without error.
    - timestamp::Int64 : Execution time in milliseconds since the Unix epoch.
    - user_name::String : User that executed the statement.
"""
Base.@kwdef mutable struct AdminAuditLogEntry <: OpenAPI.APIModel
    allow_full_table::Union{Nothing, Bool} = nothing
    committed::Union{Nothing, Bool} = nothing
    error::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing
    is_write::Union{Nothing, Bool} = nothing
    rows_affected::Union{Nothing, Int64} = nothing
    sql_text::Union{Nothing, String} = nothing
    success::Union{Nothing, Bool} = nothing
    timestamp::Union{Nothing, Int64} = nothing
    user_name::Union{Nothing, String} = nothing

    function AdminAuditLogEntry(allow_full_table, committed, error, id, is_write, rows_affected, sql_text, success, timestamp, user_name, )
        o = new(allow_full_table, committed, error, id, is_write, rows_affected, sql_text, success, timestamp, user_name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AdminAuditLogEntry

const _property_types_AdminAuditLogEntry = Dict{Symbol,String}(Symbol("allow_full_table")=>"Bool", Symbol("committed")=>"Bool", Symbol("error")=>"String", Symbol("id")=>"Int64", Symbol("is_write")=>"Bool", Symbol("rows_affected")=>"Int64", Symbol("sql_text")=>"String", Symbol("success")=>"Bool", Symbol("timestamp")=>"Int64", Symbol("user_name")=>"String", )
OpenAPI.property_type(::Type{ AdminAuditLogEntry }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminAuditLogEntry[name]))}

function OpenAPI.check_required(o::AdminAuditLogEntry)
    o.allow_full_table === nothing && (return false)
    o.committed === nothing && (return false)
    o.id === nothing && (return false)
    o.is_write === nothing && (return false)
    o.sql_text === nothing && (return false)
    o.success === nothing && (return false)
    o.timestamp === nothing && (return false)
    o.user_name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AdminAuditLogEntry)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("allow_full_table"), o.allow_full_table)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("committed"), o.committed)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("error"), o.error)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("id"), o.id)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("is_write"), o.is_write)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("rows_affected"), o.rows_affected)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("sql_text"), o.sql_text)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("success"), o.success)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("timestamp"), o.timestamp)
    OpenAPI.validate_property(AdminAuditLogEntry, Symbol("user_name"), o.user_name)
end

function OpenAPI.validate_property(::Type{ AdminAuditLogEntry }, name::Symbol, val)




    if name === Symbol("id")
        OpenAPI.validate_param(name, "AdminAuditLogEntry", :format, val, "int64")
    end


    if name === Symbol("rows_affected")
        OpenAPI.validate_param(name, "AdminAuditLogEntry", :format, val, "int64")
    end



    if name === Symbol("timestamp")
        OpenAPI.validate_param(name, "AdminAuditLogEntry", :format, val, "int64")
    end

end
