# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_datasets_response
Response for listing datasets.

    ListDatasetsResponse(;
        items=nothing,
        offset=nothing,
        count=nothing,
        total_count=nothing,
        max_limit=nothing,
        has_more=nothing,
    )

    - items::Vector{DatasetModel}
    - offset::Int64
    - count::Int64
    - total_count::Int64
    - max_limit::Int64
    - has_more::Bool
"""
Base.@kwdef mutable struct ListDatasetsResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{DatasetModel} }
    offset::Union{Nothing, Int64} = nothing
    count::Union{Nothing, Int64} = nothing
    total_count::Union{Nothing, Int64} = nothing
    max_limit::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing

    function ListDatasetsResponse(items, offset, count, total_count, max_limit, has_more, )
        o = new(items, offset, count, total_count, max_limit, has_more, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListDatasetsResponse

const _property_types_ListDatasetsResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{DatasetModel}", Symbol("offset")=>"Int64", Symbol("count")=>"Int64", Symbol("total_count")=>"Int64", Symbol("max_limit")=>"Int64", Symbol("has_more")=>"Bool", )
OpenAPI.property_type(::Type{ ListDatasetsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListDatasetsResponse[name]))}

function OpenAPI.check_required(o::ListDatasetsResponse)
    true
end

function OpenAPI.validate_properties(o::ListDatasetsResponse)
    OpenAPI.validate_property(ListDatasetsResponse, Symbol("items"), o.items)
    OpenAPI.validate_property(ListDatasetsResponse, Symbol("offset"), o.offset)
    OpenAPI.validate_property(ListDatasetsResponse, Symbol("count"), o.count)
    OpenAPI.validate_property(ListDatasetsResponse, Symbol("total_count"), o.total_count)
    OpenAPI.validate_property(ListDatasetsResponse, Symbol("max_limit"), o.max_limit)
    OpenAPI.validate_property(ListDatasetsResponse, Symbol("has_more"), o.has_more)
end

function OpenAPI.validate_property(::Type{ ListDatasetsResponse }, name::Symbol, val)






end
