# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ArchiveWorkflowRequest
Request body for &#x60;POST /workflows/{id}/archive&#x60;. Setting &#x60;is_archived&#x60; to true marks the workflow as archived; false unarchives it.

    ArchiveWorkflowRequest(;
        is_archived=nothing,
    )

    - is_archived::Bool
"""
Base.@kwdef mutable struct ArchiveWorkflowRequest <: OpenAPI.APIModel
    is_archived::Union{Nothing, Bool} = nothing

    function ArchiveWorkflowRequest(is_archived, )
        o = new(is_archived, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ArchiveWorkflowRequest

const _property_types_ArchiveWorkflowRequest = Dict{Symbol,String}(Symbol("is_archived")=>"Bool", )
OpenAPI.property_type(::Type{ ArchiveWorkflowRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ArchiveWorkflowRequest[name]))}

function OpenAPI.check_required(o::ArchiveWorkflowRequest)
    o.is_archived === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ArchiveWorkflowRequest)
    OpenAPI.validate_property(ArchiveWorkflowRequest, Symbol("is_archived"), o.is_archived)
end

function OpenAPI.validate_property(::Type{ ArchiveWorkflowRequest }, name::Symbol, val)

end
