# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AdminSqlRequest(BaseModel):
    """
    Request body for the admin raw-SQL endpoint (`POST /admin/sql`).
    """ # noqa: E501
    allow_full_table: Optional[StrictBool] = Field(default=None, description="Permit an unqualified UPDATE/DELETE (no WHERE clause). Ignored on the read-only path.")
    dry_run: Optional[StrictBool] = Field(default=None, description="Write path only: run inside a transaction, report rows affected, then roll back instead of committing (preview).")
    limit: Optional[StrictInt] = Field(default=None, description="Maximum number of SELECT result rows to return. Defaults to and is capped at 10,000 (the standard list cap); values above the cap are clamped.")
    sql: StrictStr = Field(description="The single SQL statement to execute.")
    write: Optional[StrictBool] = Field(default=None, description="Opt into the write path. When false (default) the statement runs on a read-only connection, so any write fails at the SQLite layer.")
    __properties: ClassVar[List[str]] = ["allow_full_table", "dry_run", "limit", "sql", "write"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminSqlRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if limit (nullable) is None
        # and model_fields_set contains the field
        if self.limit is None and "limit" in self.model_fields_set:
            _dict['limit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminSqlRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allow_full_table": obj.get("allow_full_table"),
            "dry_run": obj.get("dry_run"),
            "limit": obj.get("limit"),
            "sql": obj.get("sql"),
            "write": obj.get("write")
        })
        return _obj


