# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AdminAuditLogEntry(BaseModel):
    """
    One row of the admin raw-SQL audit log (`admin_audit_log`), returned by `GET /admin/audit-log` (`torc admin list-audit-log`).
    """ # noqa: E501
    allow_full_table: StrictBool = Field(description="True when the full-table guard was overridden for this statement.")
    committed: StrictBool = Field(description="True when the write was committed to the database.")
    error: Optional[StrictStr] = Field(default=None, description="Error message captured for a failed statement, when applicable.")
    id: StrictInt = Field(description="Auto-increment row id.")
    is_write: StrictBool = Field(description="True for write-path statements (all audited rows are writes).")
    rows_affected: Optional[StrictInt] = Field(default=None, description="Rows affected by the statement, when known.")
    sql_text: StrictStr = Field(description="The SQL statement text.")
    success: StrictBool = Field(description="True when the statement executed without error.")
    timestamp: StrictInt = Field(description="Execution time in milliseconds since the Unix epoch.")
    user_name: StrictStr = Field(description="User that executed the statement.")
    __properties: ClassVar[List[str]] = ["allow_full_table", "committed", "error", "id", "is_write", "rows_affected", "sql_text", "success", "timestamp", "user_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminAuditLogEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if rows_affected (nullable) is None
        # and model_fields_set contains the field
        if self.rows_affected is None and "rows_affected" in self.model_fields_set:
            _dict['rows_affected'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminAuditLogEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allow_full_table": obj.get("allow_full_table"),
            "committed": obj.get("committed"),
            "error": obj.get("error"),
            "id": obj.get("id"),
            "is_write": obj.get("is_write"),
            "rows_affected": obj.get("rows_affected"),
            "sql_text": obj.get("sql_text"),
            "success": obj.get("success"),
            "timestamp": obj.get("timestamp"),
            "user_name": obj.get("user_name")
        })
        return _obj


