# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AdminSqlResponse(BaseModel):
    """
    Response body for the admin raw-SQL endpoint (`POST /admin/sql`).
    """ # noqa: E501
    columns: List[StrictStr] = Field(description="Column names in result order, defining how `items` is displayed (empty for write statements). Names the query repeats are suffixed (`id`, `id_2`, ...) so each item's keys stay unique.")
    committed: StrictBool = Field(description="True when a write was committed to the database.")
    items: List[Dict[str, Any]] = Field(description="Result rows as objects keyed by `columns` (empty for write statements).")
    rows_affected: Optional[StrictInt] = Field(default=None, description="Number of rows affected by a write statement, when applicable.")
    __properties: ClassVar[List[str]] = ["columns", "committed", "items", "rows_affected"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminSqlResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rows_affected (nullable) is None
        # and model_fields_set contains the field
        if self.rows_affected is None and "rows_affected" in self.model_fields_set:
            _dict['rows_affected'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminSqlResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "columns": obj.get("columns"),
            "committed": obj.get("committed"),
            "items": obj.get("items"),
            "rows_affected": obj.get("rows_affected")
        })
        return _obj


