# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ClaimJobsSortMethod(str, Enum):
    """
    ClaimJobsSortMethod
    """

    """
    allowed enum values
    """
    GPUS_RUNTIME_MEMORY = 'gpus_runtime_memory'
    GPUS_MEMORY_RUNTIME = 'gpus_memory_runtime'
    NONE = 'none'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ClaimJobsSortMethod from a JSON string"""
        return cls(json.loads(json_str))


