# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.18.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from torc.openapi_client.models.execution_mode import ExecutionMode
from torc.openapi_client.models.stdio_config import StdioConfig
from typing import Optional, Set
from typing_extensions import Self

class ExecutionConfig(BaseModel):
    """
    Unified execution configuration that controls how jobs are run.  Used both as the user-authored `WorkflowSpec.execution_config` and as the persisted `WorkflowModel.execution_config` (stored as JSON in the `workflow.execution_config` column).
    """ # noqa: E501
    enable_cpu_bind: Optional[StrictBool] = Field(default=None, description="When true, allow Slurm to bind tasks to specific CPU cores (slurm mode only).")
    job_stdio_overrides: Optional[Dict[str, StdioConfig]] = Field(default=None, description="Per-job stdio overrides keyed by job name. Populated during workflow creation from per-job `stdio` fields in the spec.")
    limit_resources: Optional[StrictBool] = Field(default=None, description="When true (default), monitor memory/CPU usage and kill jobs that exceed their resource requirements (OOM enforcement). Only applies in direct mode.")
    mode: Optional[ExecutionMode] = Field(default=None, description="Execution mode: direct (default), slurm, or auto.")
    oom_exit_code: Optional[StrictInt] = Field(default=None, description="Exit code to use when a job is OOM-killed (direct mode only). Default: 137 (128 + SIGKILL = 128 + 9).")
    sigkill_headroom_seconds: Optional[StrictInt] = Field(default=None, description="Seconds before end_time to send SIGKILL (direct mode) or set srun --time (slurm mode). Default: 60.")
    sigterm_lead_seconds: Optional[StrictInt] = Field(default=None, description="Seconds before SIGKILL to send the termination signal (direct mode only). Default: 30.")
    srun_mpi: Optional[StrictStr] = Field(default=None, description="MPI launcher mode for the outer `srun` used to launch one job runner per allocated node.")
    srun_termination_signal: Optional[StrictStr] = Field(default=None, description="Signal specification for srun steps, passed as `srun --signal=<value>` (slurm mode only).")
    staggered_start: Optional[StrictBool] = Field(default=None, description="Enable staggered startup for job runners to mitigate thundering herd.")
    stdio: Optional[StdioConfig] = Field(default=None, description="Workflow-level default for stdout/stderr capture.")
    termination_signal: Optional[StrictStr] = Field(default=None, description="Signal to send before SIGKILL for graceful termination (direct mode only). Default: \"SIGTERM\".")
    timeout_exit_code: Optional[StrictInt] = Field(default=None, description="Exit code to use when a job times out. Default: 152 (matches Slurm's TIMEOUT exit code).")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["enable_cpu_bind", "job_stdio_overrides", "limit_resources", "mode", "oom_exit_code", "sigkill_headroom_seconds", "sigterm_lead_seconds", "srun_mpi", "srun_termination_signal", "staggered_start", "stdio", "termination_signal", "timeout_exit_code"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in job_stdio_overrides (dict)
        _field_dict = {}
        if self.job_stdio_overrides:
            for _key_job_stdio_overrides in self.job_stdio_overrides:
                if self.job_stdio_overrides[_key_job_stdio_overrides]:
                    _field_dict[_key_job_stdio_overrides] = self.job_stdio_overrides[_key_job_stdio_overrides].to_dict()
            _dict['job_stdio_overrides'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of stdio
        if self.stdio:
            _dict['stdio'] = self.stdio.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enable_cpu_bind": obj.get("enable_cpu_bind"),
            "job_stdio_overrides": dict(
                (_k, StdioConfig.from_dict(_v))
                for _k, _v in obj["job_stdio_overrides"].items()
            )
            if obj.get("job_stdio_overrides") is not None
            else None,
            "limit_resources": obj.get("limit_resources"),
            "mode": obj.get("mode"),
            "oom_exit_code": obj.get("oom_exit_code"),
            "sigkill_headroom_seconds": obj.get("sigkill_headroom_seconds"),
            "sigterm_lead_seconds": obj.get("sigterm_lead_seconds"),
            "srun_mpi": obj.get("srun_mpi"),
            "srun_termination_signal": obj.get("srun_termination_signal"),
            "staggered_start": obj.get("staggered_start"),
            "stdio": StdioConfig.from_dict(obj["stdio"]) if obj.get("stdio") is not None else None,
            "termination_signal": obj.get("termination_signal"),
            "timeout_exit_code": obj.get("timeout_exit_code")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


