# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.21.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExecutionMode(str, Enum):
    """
    Execution mode for job processes.  Controls how torc manages job processes during execution, particularly around termination and resource enforcement.
    """

    """
    allowed enum values
    """
    DIRECT = 'direct'
    SLURM = 'slurm'
    AUTO = 'auto'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExecutionMode from a JSON string"""
        return cls(json.loads(json_str))


