# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.23.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from torc.openapi_client.models.compute_node_schedule import ComputeNodeSchedule
from torc.openapi_client.models.job_status import JobStatus
from typing import Optional, Set
from typing_extensions import Self

class JobModel(BaseModel):
    """
    JobModel
    """ # noqa: E501
    attempt_id: Optional[StrictInt] = None
    cancel_on_blocking_job_failure: Optional[StrictBool] = None
    command: StrictStr
    compute_node_id: Optional[StrictInt] = Field(default=None, description="Compute node executing the current attempt. Set by start_job and cleared by complete_job and the reset/retry paths. For completed attempts, the compute node is recorded on the result record.")
    depends_on_job_ids: Optional[List[StrictInt]] = None
    env: Optional[Dict[str, StrictStr]] = None
    failure_handler_id: Optional[StrictInt] = None
    id: Optional[StrictInt] = None
    input_file_ids: Optional[List[StrictInt]] = None
    input_user_data_ids: Optional[List[StrictInt]] = None
    invocation_script: Optional[StrictStr] = None
    name: StrictStr
    origin: Optional[StrictStr] = Field(default=None, description="Provenance marker: NULL for jobs declared at workflow creation, `\"retry\"` for jobs resurrected by failure-handler retries, `\"spawn\"` for jobs added at runtime by `spawn_jobs`. `torc watch --auto-schedule` uses this to detect jobs that need unplanned Slurm allocations (deferred `schedule_nodes` actions only account for the originally-declared workload).")
    output_file_ids: Optional[List[StrictInt]] = None
    output_user_data_ids: Optional[List[StrictInt]] = None
    priority: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=0, description="Scheduling priority; higher values are submitted first. Minimum 0, default 0.")
    resource_requirements_id: Optional[StrictInt] = None
    schedule_compute_nodes: Optional[ComputeNodeSchedule] = None
    scheduler_id: Optional[StrictInt] = None
    start_time: Optional[StrictStr] = Field(default=None, description="Timestamp when the current attempt began running. Set by start_job and cleared by complete_job and the reset/retry paths. NULL when the job is not running (use `status` as the source of truth for \"is running\").")
    status: Optional[JobStatus] = None
    supports_termination: Optional[StrictBool] = None
    workflow_id: StrictInt
    __properties: ClassVar[List[str]] = ["attempt_id", "cancel_on_blocking_job_failure", "command", "compute_node_id", "depends_on_job_ids", "env", "failure_handler_id", "id", "input_file_ids", "input_user_data_ids", "invocation_script", "name", "origin", "output_file_ids", "output_user_data_ids", "priority", "resource_requirements_id", "schedule_compute_nodes", "scheduler_id", "start_time", "status", "supports_termination", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of schedule_compute_nodes
        if self.schedule_compute_nodes:
            _dict['schedule_compute_nodes'] = self.schedule_compute_nodes.to_dict()
        # set to None if attempt_id (nullable) is None
        # and model_fields_set contains the field
        if self.attempt_id is None and "attempt_id" in self.model_fields_set:
            _dict['attempt_id'] = None

        # set to None if cancel_on_blocking_job_failure (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_on_blocking_job_failure is None and "cancel_on_blocking_job_failure" in self.model_fields_set:
            _dict['cancel_on_blocking_job_failure'] = None

        # set to None if compute_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_id is None and "compute_node_id" in self.model_fields_set:
            _dict['compute_node_id'] = None

        # set to None if depends_on_job_ids (nullable) is None
        # and model_fields_set contains the field
        if self.depends_on_job_ids is None and "depends_on_job_ids" in self.model_fields_set:
            _dict['depends_on_job_ids'] = None

        # set to None if failure_handler_id (nullable) is None
        # and model_fields_set contains the field
        if self.failure_handler_id is None and "failure_handler_id" in self.model_fields_set:
            _dict['failure_handler_id'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if input_file_ids (nullable) is None
        # and model_fields_set contains the field
        if self.input_file_ids is None and "input_file_ids" in self.model_fields_set:
            _dict['input_file_ids'] = None

        # set to None if input_user_data_ids (nullable) is None
        # and model_fields_set contains the field
        if self.input_user_data_ids is None and "input_user_data_ids" in self.model_fields_set:
            _dict['input_user_data_ids'] = None

        # set to None if invocation_script (nullable) is None
        # and model_fields_set contains the field
        if self.invocation_script is None and "invocation_script" in self.model_fields_set:
            _dict['invocation_script'] = None

        # set to None if origin (nullable) is None
        # and model_fields_set contains the field
        if self.origin is None and "origin" in self.model_fields_set:
            _dict['origin'] = None

        # set to None if output_file_ids (nullable) is None
        # and model_fields_set contains the field
        if self.output_file_ids is None and "output_file_ids" in self.model_fields_set:
            _dict['output_file_ids'] = None

        # set to None if output_user_data_ids (nullable) is None
        # and model_fields_set contains the field
        if self.output_user_data_ids is None and "output_user_data_ids" in self.model_fields_set:
            _dict['output_user_data_ids'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if resource_requirements_id (nullable) is None
        # and model_fields_set contains the field
        if self.resource_requirements_id is None and "resource_requirements_id" in self.model_fields_set:
            _dict['resource_requirements_id'] = None

        # set to None if scheduler_id (nullable) is None
        # and model_fields_set contains the field
        if self.scheduler_id is None and "scheduler_id" in self.model_fields_set:
            _dict['scheduler_id'] = None

        # set to None if start_time (nullable) is None
        # and model_fields_set contains the field
        if self.start_time is None and "start_time" in self.model_fields_set:
            _dict['start_time'] = None

        # set to None if supports_termination (nullable) is None
        # and model_fields_set contains the field
        if self.supports_termination is None and "supports_termination" in self.model_fields_set:
            _dict['supports_termination'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attempt_id": obj.get("attempt_id"),
            "cancel_on_blocking_job_failure": obj.get("cancel_on_blocking_job_failure"),
            "command": obj.get("command"),
            "compute_node_id": obj.get("compute_node_id"),
            "depends_on_job_ids": obj.get("depends_on_job_ids"),
            "env": obj.get("env"),
            "failure_handler_id": obj.get("failure_handler_id"),
            "id": obj.get("id"),
            "input_file_ids": obj.get("input_file_ids"),
            "input_user_data_ids": obj.get("input_user_data_ids"),
            "invocation_script": obj.get("invocation_script"),
            "name": obj.get("name"),
            "origin": obj.get("origin"),
            "output_file_ids": obj.get("output_file_ids"),
            "output_user_data_ids": obj.get("output_user_data_ids"),
            "priority": obj.get("priority") if obj.get("priority") is not None else 0,
            "resource_requirements_id": obj.get("resource_requirements_id"),
            "schedule_compute_nodes": ComputeNodeSchedule.from_dict(obj["schedule_compute_nodes"]) if obj.get("schedule_compute_nodes") is not None else None,
            "scheduler_id": obj.get("scheduler_id"),
            "start_time": obj.get("start_time"),
            "status": obj.get("status"),
            "supports_termination": obj.get("supports_termination"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


