# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.23.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MonitorGranularity(str, Enum):
    """
    Granularity for resource monitoring sampling.
    """

    """
    allowed enum values
    """
    SUMMARY = 'summary'
    TIME_SERIES = 'time_series'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MonitorGranularity from a JSON string"""
        return cls(json.loads(json_str))


