# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.17.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from torc.openapi_client.models.compute_node_monitor_config import ComputeNodeMonitorConfig
from torc.openapi_client.models.job_monitor_config import JobMonitorConfig
from torc.openapi_client.models.monitor_granularity import MonitorGranularity
from typing import Optional, Set
from typing_extensions import Self

class ResourceMonitorConfig(BaseModel):
    """
    Configuration for resource monitoring.  Used both as the user-authored `WorkflowSpec.resource_monitor` and as the persisted `WorkflowModel.resource_monitor_config` (stored as JSON in the `workflow.resource_monitor_config` column).
    """ # noqa: E501
    compute_node: Optional[ComputeNodeMonitorConfig] = None
    enabled: Optional[StrictBool] = Field(default=False, description="Deprecated compatibility field. Use `jobs.enabled` for new workflow specs.")
    flush_interval_seconds: Optional[StrictInt] = Field(default=300, description="How often buffered time-series samples are flushed to SQLite, in seconds.")
    generate_plots: Optional[StrictBool] = False
    granularity: Optional[MonitorGranularity] = Field(default=None, description="Deprecated compatibility field. Use `jobs.granularity` for new workflow specs.")
    jobs: Optional[JobMonitorConfig] = None
    sample_interval_seconds: Optional[StrictInt] = 10
    __properties: ClassVar[List[str]] = ["compute_node", "enabled", "flush_interval_seconds", "generate_plots", "granularity", "jobs", "sample_interval_seconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceMonitorConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of compute_node
        if self.compute_node:
            _dict['compute_node'] = self.compute_node.to_dict()
        # override the default output from pydantic by calling `to_dict()` of jobs
        if self.jobs:
            _dict['jobs'] = self.jobs.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceMonitorConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compute_node": ComputeNodeMonitorConfig.from_dict(obj["compute_node"]) if obj.get("compute_node") is not None else None,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else False,
            "flush_interval_seconds": obj.get("flush_interval_seconds") if obj.get("flush_interval_seconds") is not None else 300,
            "generate_plots": obj.get("generate_plots") if obj.get("generate_plots") is not None else False,
            "granularity": obj.get("granularity"),
            "jobs": JobMonitorConfig.from_dict(obj["jobs"]) if obj.get("jobs") is not None else None,
            "sample_interval_seconds": obj.get("sample_interval_seconds") if obj.get("sample_interval_seconds") is not None else 10
        })
        return _obj


