# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.17.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SpawnJobModel(BaseModel):
    """
    One job to add atomically as part of `spawn_jobs`.  `depends_on` entries may reference jobs that already exist in the workflow or sibling jobs created in the same request (resolved by name within the transaction). Every spawned job is created `blocked` — the server auto- injects a dependency edge to the calling job in addition to any explicit `depends_on`, so spawned jobs are promoted by the normal background unblock path once the caller (and any explicit deps) become terminal.
    """ # noqa: E501
    cancel_on_blocking_job_failure: Optional[StrictBool] = None
    command: StrictStr
    depends_on: Optional[List[StrictStr]] = Field(default=None, description="Job names this job depends on (existing jobs or siblings in this batch).")
    name: StrictStr
    priority: Optional[StrictInt] = None
    resource_requirements: Optional[StrictStr] = Field(default=None, description="Name of an existing resource_requirements record in the workflow.")
    __properties: ClassVar[List[str]] = ["cancel_on_blocking_job_failure", "command", "depends_on", "name", "priority", "resource_requirements"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpawnJobModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cancel_on_blocking_job_failure (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_on_blocking_job_failure is None and "cancel_on_blocking_job_failure" in self.model_fields_set:
            _dict['cancel_on_blocking_job_failure'] = None

        # set to None if depends_on (nullable) is None
        # and model_fields_set contains the field
        if self.depends_on is None and "depends_on" in self.model_fields_set:
            _dict['depends_on'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if resource_requirements (nullable) is None
        # and model_fields_set contains the field
        if self.resource_requirements is None and "resource_requirements" in self.model_fields_set:
            _dict['resource_requirements'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpawnJobModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cancel_on_blocking_job_failure": obj.get("cancel_on_blocking_job_failure"),
            "command": obj.get("command"),
            "depends_on": obj.get("depends_on"),
            "name": obj.get("name"),
            "priority": obj.get("priority"),
            "resource_requirements": obj.get("resource_requirements")
        })
        return _obj


