# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.23.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from torc.openapi_client.models.spawn_job_model import SpawnJobModel
from typing import Optional, Set
from typing_extensions import Self

class SpawnJobsRequest(BaseModel):
    """
    Add a batch of new jobs to an initialized workflow, all blocked on the calling job. The calling job is **not** completed by this call — the orchestrator script exits normally and the runner completes it, at which point the unblock cascade promotes the spawned jobs.  The per-lineage spawn-iteration counter is advanced and an opaque state payload is persisted, all in the same transaction as the inserts.
    """ # noqa: E501
    jobs: List[SpawnJobModel] = Field(description="Jobs to add. May be empty (record final state without spawning).")
    lineage: Optional[StrictStr] = Field(default=None, description="Orchestrator lineage identifier. Defaults to the calling job's name. The per-lineage spawn counter and state records are keyed on this.")
    state: Optional[Any] = Field(default=None, description="Opaque JSON state attached to this generation (or as the converged final state when `jobs` is empty).")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["jobs", "lineage", "state"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpawnJobsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in jobs (list)
        _items = []
        if self.jobs:
            for _item_jobs in self.jobs:
                if _item_jobs:
                    _items.append(_item_jobs.to_dict())
            _dict['jobs'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpawnJobsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jobs": [SpawnJobModel.from_dict(_item) for _item in obj["jobs"]] if obj.get("jobs") is not None else None,
            "lineage": obj.get("lineage"),
            "state": obj.get("state")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


