# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StdioMode(str, Enum):
    """
    How to capture stdout and stderr for job processes.
    """

    """
    allowed enum values
    """
    SEPARATE = 'separate'
    COMBINED = 'combined'
    NO_STDOUT = 'no_stdout'
    NO_STDERR = 'no_stderr'
    NONE = 'none'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StdioMode from a JSON string"""
        return cls(json.loads(json_str))


