# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.17.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from torc.openapi_client.models.dynamic_jobs_config import DynamicJobsConfig
from torc.openapi_client.models.execution_config import ExecutionConfig
from torc.openapi_client.models.resource_monitor_config import ResourceMonitorConfig
from typing import Optional, Set
from typing_extensions import Self

class WorkflowModel(BaseModel):
    """
    WorkflowModel
    """ # noqa: E501
    compute_node_expiration_buffer_seconds: Optional[StrictInt] = None
    compute_node_ignore_workflow_completion: Optional[StrictBool] = None
    compute_node_min_time_for_new_jobs_seconds: Optional[StrictInt] = None
    compute_node_wait_for_healthy_database_minutes: Optional[StrictInt] = None
    compute_node_wait_for_new_jobs_seconds: Optional[StrictInt] = None
    description: Optional[StrictStr] = None
    dynamic_jobs: Optional[DynamicJobsConfig] = Field(default=None, description="Dynamic job spawning configuration. Mirrors the workflow-spec `dynamic_jobs` section identically. Runtime-immutable after workflow creation.")
    enable_ro_crate: Optional[StrictBool] = None
    env: Optional[Dict[str, StrictStr]] = None
    execution_config: Optional[ExecutionConfig] = None
    id: Optional[StrictInt] = None
    is_archived: Optional[StrictBool] = Field(default=None, description="True when the workflow has been archived. Read-only on the API: set via `POST /workflows/{id}/archive`, cleared via `POST /workflows/{id}/reset_status`. Values supplied to create/update workflow endpoints are ignored.")
    is_canceled: Optional[StrictBool] = Field(default=None, description="True when a user (or scheduler) has canceled the workflow. Read-only on the API: set via `POST /workflows/{id}/cancel`, cleared via `POST /workflows/{id}/reset_status`. Values supplied to create/update workflow endpoints are ignored.")
    metadata: Optional[Dict[str, Any]] = None
    name: StrictStr
    project: Optional[StrictStr] = None
    resource_monitor_config: Optional[ResourceMonitorConfig] = None
    run_id: Optional[StrictInt] = Field(default=None, description="Current run number; incremented on each restart/recovery. Read-only on the API: incremented as a side effect of `POST /workflows/{id}/reset_status`. Values supplied to create/update workflow endpoints are ignored.")
    slurm_defaults: Optional[Dict[str, Any]] = None
    timestamp: Optional[StrictStr] = None
    use_pending_failed: Optional[StrictBool] = None
    user: StrictStr
    __properties: ClassVar[List[str]] = ["compute_node_expiration_buffer_seconds", "compute_node_ignore_workflow_completion", "compute_node_min_time_for_new_jobs_seconds", "compute_node_wait_for_healthy_database_minutes", "compute_node_wait_for_new_jobs_seconds", "description", "dynamic_jobs", "enable_ro_crate", "env", "execution_config", "id", "is_archived", "is_canceled", "metadata", "name", "project", "resource_monitor_config", "run_id", "slurm_defaults", "timestamp", "use_pending_failed", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "is_archived",
            "is_canceled",
            "run_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dynamic_jobs
        if self.dynamic_jobs:
            _dict['dynamic_jobs'] = self.dynamic_jobs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of execution_config
        if self.execution_config:
            _dict['execution_config'] = self.execution_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resource_monitor_config
        if self.resource_monitor_config:
            _dict['resource_monitor_config'] = self.resource_monitor_config.to_dict()
        # set to None if compute_node_expiration_buffer_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_expiration_buffer_seconds is None and "compute_node_expiration_buffer_seconds" in self.model_fields_set:
            _dict['compute_node_expiration_buffer_seconds'] = None

        # set to None if compute_node_ignore_workflow_completion (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_ignore_workflow_completion is None and "compute_node_ignore_workflow_completion" in self.model_fields_set:
            _dict['compute_node_ignore_workflow_completion'] = None

        # set to None if compute_node_min_time_for_new_jobs_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_min_time_for_new_jobs_seconds is None and "compute_node_min_time_for_new_jobs_seconds" in self.model_fields_set:
            _dict['compute_node_min_time_for_new_jobs_seconds'] = None

        # set to None if compute_node_wait_for_healthy_database_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_wait_for_healthy_database_minutes is None and "compute_node_wait_for_healthy_database_minutes" in self.model_fields_set:
            _dict['compute_node_wait_for_healthy_database_minutes'] = None

        # set to None if compute_node_wait_for_new_jobs_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_wait_for_new_jobs_seconds is None and "compute_node_wait_for_new_jobs_seconds" in self.model_fields_set:
            _dict['compute_node_wait_for_new_jobs_seconds'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if enable_ro_crate (nullable) is None
        # and model_fields_set contains the field
        if self.enable_ro_crate is None and "enable_ro_crate" in self.model_fields_set:
            _dict['enable_ro_crate'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if is_archived (nullable) is None
        # and model_fields_set contains the field
        if self.is_archived is None and "is_archived" in self.model_fields_set:
            _dict['is_archived'] = None

        # set to None if is_canceled (nullable) is None
        # and model_fields_set contains the field
        if self.is_canceled is None and "is_canceled" in self.model_fields_set:
            _dict['is_canceled'] = None

        # set to None if project (nullable) is None
        # and model_fields_set contains the field
        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        # set to None if run_id (nullable) is None
        # and model_fields_set contains the field
        if self.run_id is None and "run_id" in self.model_fields_set:
            _dict['run_id'] = None

        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        # set to None if use_pending_failed (nullable) is None
        # and model_fields_set contains the field
        if self.use_pending_failed is None and "use_pending_failed" in self.model_fields_set:
            _dict['use_pending_failed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compute_node_expiration_buffer_seconds": obj.get("compute_node_expiration_buffer_seconds"),
            "compute_node_ignore_workflow_completion": obj.get("compute_node_ignore_workflow_completion"),
            "compute_node_min_time_for_new_jobs_seconds": obj.get("compute_node_min_time_for_new_jobs_seconds"),
            "compute_node_wait_for_healthy_database_minutes": obj.get("compute_node_wait_for_healthy_database_minutes"),
            "compute_node_wait_for_new_jobs_seconds": obj.get("compute_node_wait_for_new_jobs_seconds"),
            "description": obj.get("description"),
            "dynamic_jobs": DynamicJobsConfig.from_dict(obj["dynamic_jobs"]) if obj.get("dynamic_jobs") is not None else None,
            "enable_ro_crate": obj.get("enable_ro_crate"),
            "env": obj.get("env"),
            "execution_config": ExecutionConfig.from_dict(obj["execution_config"]) if obj.get("execution_config") is not None else None,
            "id": obj.get("id"),
            "is_archived": obj.get("is_archived"),
            "is_canceled": obj.get("is_canceled"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name"),
            "project": obj.get("project"),
            "resource_monitor_config": ResourceMonitorConfig.from_dict(obj["resource_monitor_config"]) if obj.get("resource_monitor_config") is not None else None,
            "run_id": obj.get("run_id"),
            "slurm_defaults": obj.get("slurm_defaults"),
            "timestamp": obj.get("timestamp"),
            "use_pending_failed": obj.get("use_pending_failed"),
            "user": obj.get("user")
        })
        return _obj


