# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.20.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from torc.openapi_client.models.job_status_counts import JobStatusCounts
from typing import Optional, Set
from typing_extensions import Self

class WorkflowStatusResponse(BaseModel):
    """
    Aggregated status summary for a workflow, computed server-side.
    """ # noqa: E501
    active_compute_nodes: StrictInt
    active_scheduled_nodes: StrictInt
    is_canceled: StrictBool
    is_complete: StrictBool
    jobs_by_status: JobStatusCounts
    pending_scheduled_nodes: StrictInt
    total_exec_time_minutes: Union[StrictFloat, StrictInt]
    total_jobs: StrictInt
    walltime_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    workflow_id: StrictInt
    workflow_name: StrictStr
    workflow_user: StrictStr
    __properties: ClassVar[List[str]] = ["active_compute_nodes", "active_scheduled_nodes", "is_canceled", "is_complete", "jobs_by_status", "pending_scheduled_nodes", "total_exec_time_minutes", "total_jobs", "walltime_seconds", "workflow_id", "workflow_name", "workflow_user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of jobs_by_status
        if self.jobs_by_status:
            _dict['jobs_by_status'] = self.jobs_by_status.to_dict()
        # set to None if walltime_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.walltime_seconds is None and "walltime_seconds" in self.model_fields_set:
            _dict['walltime_seconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active_compute_nodes": obj.get("active_compute_nodes"),
            "active_scheduled_nodes": obj.get("active_scheduled_nodes"),
            "is_canceled": obj.get("is_canceled"),
            "is_complete": obj.get("is_complete"),
            "jobs_by_status": JobStatusCounts.from_dict(obj["jobs_by_status"]) if obj.get("jobs_by_status") is not None else None,
            "pending_scheduled_nodes": obj.get("pending_scheduled_nodes"),
            "total_exec_time_minutes": obj.get("total_exec_time_minutes"),
            "total_jobs": obj.get("total_jobs"),
            "walltime_seconds": obj.get("walltime_seconds"),
            "workflow_id": obj.get("workflow_id"),
            "workflow_name": obj.get("workflow_name"),
            "workflow_user": obj.get("workflow_user")
        })
        return _obj


