//! Backwards-compatible API re-exports.
//!
//! Older tests and callers expect a `client::default_api` module generated by
//! the OpenAPI client. The current generated client splits endpoints across
//! resource-specific modules, so this module preserves the old surface by
//! re-exporting the commonly used functions.

pub use crate::client::apis::access_control_api::{
    add_user_to_group, add_workflow_to_group, check_workflow_access, create_access_group,
    delete_access_group, get_access_group, list_access_groups, list_group_members,
    list_user_groups, list_workflow_groups, remove_user_from_group, remove_workflow_from_group,
};
pub use crate::client::apis::compute_nodes_api::create_compute_node;
pub use crate::client::apis::events_api::create_event;
pub use crate::client::apis::files_api::{create_file, get_file};
pub use crate::client::apis::jobs_api::{create_job, get_job, list_jobs};
pub use crate::client::apis::resource_requirements_api::{
    create_resource_requirements, get_resource_requirements,
};
pub use crate::client::apis::results_api::create_result;
pub use crate::client::apis::user_data_api::create_user_data;
pub use crate::client::apis::workflows_api::{
    create_workflow, delete_workflow, get_workflow, initialize_jobs, list_workflows,
};
